### PR TITLE
Correct a typo in allowed method in `compare`

### PR DESCRIPTION
**Pull request by charlesdong1991**
## Description

It seems arviz allows `pseudo-BMA` instead of `pseudo-MA` as options, this PR corrects this typo.

## Checklist

- [ ] Follows [official](https://github.com/arviz-devs/arviz/blob/main/CONTRIBUTING.md#pull-request-checklist) PR format
- [ ] Includes a sample plot to visually illustrate the changes (only for plot-related functions)
- [ ] New features are properly documented (with an example if appropriate)?
- [ ] Includes new or updated tests to cover the new feature
- [ ] Code style  correct (follows pylint and black guidelines)
- [ ] Changes are listed in [changelog](https://github.com/arviz-devs/arviz/blob/main/CHANGELOG.md#v0xx-unreleased)

### CODE REVIEW

**Comment by OriolAbril** [comment]
@charlesdong1991 now that CI is fixed (again, thanks for the help), can you rebase the PR? I don't see any reason why CI would not pass with those changes but always best to check, specially for pylint/black/mypy, we might be able to improve the mypy config and ignore less errors for example

**Comment by charlesdong1991** [comment]
@OriolAbril i rebased, and CI is still good.

Small question though: any idea why mypy wasn't giving any errors before on this typo? I would assume mypy will complain given how `Literal` is being designed. 🤔 I switched import of `Literal` from `type_extension` to `typing`, but seems the same (no error).

**Comment by OriolAbril** [comment]
I have no idea.

We might be ignoring the error in https://github.com/arviz-devs/arviz/blob/main/mypy.ini or maybe the pseudo-BMA value is not used anywhere in the codebase? I'd think it has a test given its importance for the compare method, but we don't test all values of all arguments so I might be wrong here. 

Or, can mypy understand we have an `if not in` then raise error and compares the tuple there to the literal defined? That sounds a bit too good to be true to me

**Comment by charlesdong1991** [comment]
kk, there is a test indeed for checking the value. mypy only analyzes code but doesn't execute, so i think this doesn't affect code execution at all.  Probably some mypy configuration issue indeed, quite weird 🤔

**Pull request merged**
