### PR TITLE
Bugfix for  comparison exception

### PR DESCRIPTION
**Pull request by canyon289**
@ahartikainen Is this the correct fix for the issue below? Shape problems get me everytime

https://github.com/arviz-devs/arviz/issues/740

### CODE REVIEW

**Comment by OriolAbril** [comment]
@canyon289 I will take a look at it. It looks like it is probably an issue I created when modifying the `stats.py` functions to use xarray. I say so because in addition to return DataArrays instead of ndarrays, the functions are applied via apply ufunc, instead of reshaping to 2D objects `(nsamples, nobservations)` (like originally) only chain and draws are stacked `(*shape, nsamples)`.

I think that the squeeze will not probably solve the issue, because the problem is likely to be with multidimensional objects (which in general cannot be converted to 1D objects via squeeze). I may not have time until tomorrow though.

**Comment by canyon289** [comment]
No rush! Was just curious. Thanks for helping me with this.

Squeeze solved my specific example but I don't know if its generalizeable

**Comment by OriolAbril** [comment]
I have just checked the behaviour on a [2d model](https://github.com/OriolAbril/Bayesian-Inference-examples/tree/master/Binomial_on_2D_data) and got the following error:

    ValueError: could not broadcast input array from shape (13,8) into shape (13)

In this case the problem cannot be solved with a squeeze. I will send a PR with a possible fix in some minutes, and in the following weeks I will try to test all stats functions on 1D and 2D data (like it is done with plots) in order to catch these issues in CI testing.

**Comment by canyon289** [comment]
Closing in favor of https://github.com/arviz-devs/arviz/pull/748

**Pull request closed without merging**
