### PR TITLE
Update stats.py

### PR DESCRIPTION
**Pull request by nilanjan2002**
Migrated the depreciated **np.product()** to its almost equivalent function **np.prod()**
## Checklist

- [x] Follows [official](https://github.com/arviz-devs/arviz/blob/main/CONTRIBUTING.md#pull-request-checklist) PR format
- [ ] Includes a sample plot to visually illustrate the changes (only for plot-related functions)
- [ ] New features are properly documented (with an example if appropriate)?
- [ ] Includes new or updated tests to cover the new feature
- [ ] Code style  correct (follows pylint and black guidelines)
- [x] Changes are listed in [changelog](https://github.com/arviz-devs/arviz/blob/main/CHANGELOG.md#v0xx-unreleased)

----
:books: Documentation preview :books:: https://arviz--2250.org.readthedocs.build/en/2250/

### CODE REVIEW

**Comment by nilanjan2002** [comment]
Hey! I'm new to open-source contributing! Could you please guide me whether or not my change was accepted or not, if not then what should I do? Cheers!

**Comment by ahartikainen** [comment]
Hi,

I understand that you are targeting the #2248 issue. And to fix this you have created a branch in your fork. Then add the changes to the codebase and commit them to your branch (1 or more commits).

After you have done changes to your branch, you can create a pull request to arviz/main. Basically what is now done in #2249

There is no need to create pull requests to these commits separately. One PR with all the commits is enough.

So I have just cleaned the PRs in our side.

**Comment by ahartikainen** [comment]
Ok, maybe there was a different user creating the other PR?

**Comment by nilanjan2002** [comment]
Does that mean my PR get merged? I'm a bit confused! So I should've made all the fixes using one PR?

**Comment by nilanjan2002** [comment]
Hey thank you so much for helping out man! Means a lot.. I just started contributing today.

**Comment by OriolAbril** [comment]
> So I should've made all the fixes using one PR?

Yes, PRs should fix issues as a whole, even multiple issues. You can commit new changes to the same branch from which you opened the PR to add changes after opening the PR. We will merge https://github.com/arviz-devs/arviz/pull/2249 following [our guidelines](https://python.arviz.org/en/stable/contributing/contributing_prs.html#steps-before-starting-work), as @Surya-Narayan  commented on the issue first and opened the PR. They probably won't be a direct search and replace, but if you are interested in exploratory analysis of bayesian models we'll be happy to help you find another issue and review new PRs.

**Comment by nilanjan2002** [comment]
Sure! But I do not know much about statistics, but please tell me the topics and languages I should be proficient to be helpful to this project. :)

**Comment by nilanjan2002** [comment]
Thank you so much, going through it. idk if it's normal or not but the project you're mentoring **Plotting Refactoring** , seems pretty daunting to me as a beginner. Do you have any advice to me if I target GSOC 2024 with arviz, what sort of tech stacks and tools I should be using. I've not really been in data analysis that much.

**Pull request closed without merging**
