### PR TITLE
fix gaussian import from scipy

### LINKED ISSUE #2330: arviz not compatible with pre-releases
**Describe the bug**

> import arviz as az
> /opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/arviz/init.py:34: in
> from .plots import *
> /opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/arviz/plots/init.py:2: in
> from .autocorrplot import plot_autocorr
> /opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/arviz/plots/autocorrplot.py:7: in
> from .plot_utils import default_grid, filter_plotters_list, get_plotting_function
> /opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/arviz/plots/plot_utils.py:15: in
> from ..stats.density_utils import kde
> /opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/arviz/stats/init.py:3: in
> from .density_utils import *
> /opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/arviz/stats/density_utils.py:8: in
> from scipy.signal import convolve, convolve2d, gaussian # pylint: disable=no-name-in-module
> E ImportError: cannot import name 'gaussian' from 'scipy.signal' (/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/scipy/signal/init.py)

**To Reproduce**
Found it in my CI. Probably one just needs to install `arviz` with the `--pre` flag.

### PR DESCRIPTION
**Pull request by OriolAbril**
## Description
closes #2330

## Checklist

- [ ] Does the PR follow [official](https://github.com/arviz-devs/arviz/blob/main/CONTRIBUTING.md#pull-request-checklist)
      PR format?
- [ ] Does the PR include new or updated tests to prevent issue recurrence (using [pytest fixture pattern](
      https://docs.pytest.org/en/latest/fixture.html#fixture))?
- [ ] Is the code style correct (follows pylint and black guidelines)?
- [ ] Is the fix listed in the [Maintenance and fixes](https://github.com/arviz-devs/arviz/blob/main/CHANGELOG.md#maintenance-and-fixes)
      section of the changelog?

----
📚 Documentation preview 📚: https://arviz--2332.org.readthedocs.build/en/2332/

### CODE REVIEW

**Comment by tomicapretto** [comment]
Is this related to any specific version of SciPy or any detail that could be made explicit? It's just curiosity, the change looks good.

**Comment by OriolAbril** [comment]
The function has been moved, starting with next release trying to import it from scipy.signal instead of scipy.signal.windows will raise an error. The issue this PR will close is because this is already happening with the latest scipy pre-release

**Comment by juanitorduz** [comment]
Hey! as the scipy 1.13 was released yesterday (https://pypi.org/project/scipy/1.13.0/) Will you cut a release with this fix soon 🙏 ?

**Comment by zerothi** [comment]
Next time things like this happens, it would be more ideal to do something like:

```python
try:
    # import-change since version 1.13!
    from scipy.signal.windows import gaussian
except:
    from scipy.signal import gaussian
```
in this way you are backwards-compatible without these cascading problems.

**Comment by OriolAbril** [comment]
We generally do that @zerothi. However in that case the issue is we missed the DeprecationWarning, so the issue and PR were open when after the deprecation process, when `scipy.signal.gaussian` was finally removed. IIRC, `scipy.signal.gaussian` was removed in scipy 1.13, but `scipy.signal.windows.gaussian` has been around since at least [scipy 1.7](https://docs.scipy.org/doc/scipy-1.7.0/reference/reference/generated/scipy.signal.windows.gaussian.html), and ArviZ requires [scipy >=1.9](https://github.com/arviz-devs/arviz/blob/main/requirements.txt#L4). There is no version of scipy supported by ArviZ where `from scipy.signal.windows import gaussian` should fail.

Keep in mind the original code was probably written around scipy 1.0 at which time the `scipy.signal.windows` submodule didn't exist yet: https://docs.scipy.org/doc/scipy-1.0.0/reference/signal.html#window-functions and it has probably changed locations within ArviZ but mostly copy pasting to restructure imports.

**Comment by zerothi** [comment]
Ok, I agree with your comments! Thanks!!

**Comment by bob-carpenter** [comment]
I brought this up on the PyMC forums, who referred me here.

>  IIRC, scipy.signal.gaussian was removed in scipy 1.13,

This is still failing for me with a brand new Python install from homebrew and latest scipy.  

```bash
build (benchmarks)$ /opt/homebrew/bin/python3.13
Python 3.13.5 (main, Jun 11 2025, 15:36:57) [Clang 17.0.0 (clang-1700.0.13.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

>>> from scipy.signal import gaussian
Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    from scipy.signal import gaussian
ImportError: cannot import name 'gaussian' from 'scipy.signal' (/opt/homebrew/lib/python3.13/site-packages/scipy/signal/__init__.py)

>>> import scipy as sp

>>> sp.__version__
'1.16.1'
```
Is the only solution to pin a version of scipy < 1.13 in order to use ArviZ?  Or is there a branch or version of ArviZ that works with the latest scipy?

**Comment by bob-carpenter** [comment]
The problem is solved if I downgrade to scipy 1.12.

**Comment by OriolAbril** [comment]
I commented on pymc discord. Unless I misunderstood the situation you need to update how you import the gaussian window from SciPy

**Pull request merged**
