### PR TITLE
Adding requirements-test.txt

### PR DESCRIPTION
**Pull request by camillebruckmann**
## Description

Addresses issue #2084 
This pull request has two changes. The first is the addition of a file called "requirements-test.txt" which can be used to install all the dependencies required to run tests. The second is a change to "requirements-external.txt" which replaces the third requirement in the list: `pymc3 @ git+https://github.com/pymc-devs/pymc3` with `pymc3`. This change was done because [pymc3 has been replaced by pymc](https://github.com/pymc-devs/pymc/commit/8ed23e0e2619bb9c351d7709c273281724e6c641), and that requirement was throwing an error. 

## Checklist

- [x] Follows [official](https://github.com/arviz-devs/arviz/blob/main/CONTRIBUTING.md#pull-request-checklist) PR format
- [x] Code style  correct (follows pylint and black guidelines)
- [x] A PR has been submitted for changes in [changelog](https://github.com/arviz-devs/arviz/blob/main/CHANGELOG.md#v0xx-unreleased)

----
:books: Documentation preview :books:: https://arviz--2169.org.readthedocs.build/en/2169/

### CODE REVIEW

**Comment by OriolAbril** [comment]
Thanks for the PR! 

There are some tests that no longer work which I think is actually a coincidence, but on closer inspection they probably should have been failing for 5 months or so now. It turns out that pymc3 has a <1.8 cap on scipy whereas since 5 months ago arviz has >=1.8 cap on scipy, so arviz is no longer compatible with pymc3. Ref: https://dev.azure.com/ArviZ/ArviZ/_build/results?buildId=6199&view=logs&j=cc734feb-7cc6-5816-627f-a6ef20c35efd&t=e52bfebe-c6a5-5c0d-c87a-8b8b6e8f8ee1&l=52

The addition of the requirements-test file looks great. We should remove the PyMC3 external dependency and tests. This will be a bit convoluted, I am still not sure how many files we'll need to change/remove. I can take a look and do the changes myself so we can merge this PR with the requirements-test addition. If that is something that you'd be interested in however I would also be happy to help.

**Comment by camillebruckmann** [comment]
Hey! I appreciate the quick response. I would love to try and fix this issue myself. To clarify, do we want to remove all dependencies to pymc3 (i.e. remove it completely from requirements-external.txt) or should we replace it with pymc (the newer version?).

If the former is correct, my approach would be to first remove pymc3 from requirements-external.txt then to remove the tests for pymc3 in azure-pipelines-external.yml. Then, I would remove any pymc3-dependent functionality. Does this sound like a good approach?

**Comment by OriolAbril** [comment]
> To clarify, do we want to remove all dependencies to pymc3

Yes, we only install pymc3 to test the converter, the library itself works without pymc nor pymc3 installed. As it is now tested on pymc side we can safely remove this completely.

> my approach would be to first remove pymc3 from requirements-external.txt then to remove the tests for pymc3 in azure-pipelines-external.yml. Then, I would remove any pymc3-dependent functionality. Does this sound like a good approach?

That sounds great. I also took a quick look on things to update:

* ci/requirements: as you said, this means requirements-external and azure pipelines external
* tests: there is one file with pymc tests, but also some helpers to pre compile pymc3 models. both need to be removed
* pymc3 converter: this means removing the io_pymc3 files from arviz/data folder and maybe update some `__init__` files too.
* pymc3 converter docs: remove the pymc3 related methods from the autosummary in https://github.com/arviz-devs/arviz/blob/main/doc/source/api/data.rst. No need to update anything else in the docs for now.

**Comment by camillebruckmann** [comment]
Quick question: radon.py, found in arviz/data/example_data/radon, is heavily dependent on pymc3. Should I delete the file? Or should I keep it and maybe create an issue for someone to replicate its functionality without pymc?

**Comment by OriolAbril** [comment]
Thanks @camillebruckmann, I ran black to try and get tests to pass, looks like it did not work. cc @ahartikainen there is one httpstan error now in the external tests

**Review by OriolAbril — APPROVED** [review]

**Comment by camillebruckmann** [comment]
Thanks Oriol for the review! Does it look good to merge? Or is there anything else I can do to help?

**Pull request merged**
