### PR TITLE
Updates to TFP branch

### PR DESCRIPTION
**Pull request by kyleabeauchamp**
This is the same as https://github.com/arviz-devs/arviz/pull/376 but with the latest commits from master merged in.  I just want to kick off Travis to see what the remaining CI failures are...

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
This might be good to go.  I just fixed lint and test failures until the previous PR was green on Travis.

**Comment by canyon289** [comment]
@yaochitc and @kyleabeauchamp you're both champs. Thank you so much.

@kyleabeauchamp, In regards how to do correct attribution. Could you squash your commits into one? If you need help let me know and I can provide more assistance.

I would do this except if I did it would show me as the author

**Comment by kyleabeauchamp** [comment]
I think I squashed all my substantial changes into a single one, but PTAL as I rarely use rebase.

**Comment by canyon289** [comment]
@kyleabeauchamp Looks good. Once tests pass I'll merge

**Comment by canyon289** [comment]
@yaochitc If no comments I'll probably merge in ~36 hours. Can't express enough how much the help from both of you is appreciated

**Comment by yaochitc** [comment]
Sorry for missing this pr, I'll have a look at it.

**Pull request merged**
