### PR TITLE
Disallow print statements for debugging

### PR DESCRIPTION
**Pull request by MarcoGorelli**
## Checklist

- [ ] Follows [official](https://github.com/arviz-devs/arviz/blob/main/CONTRIBUTING.md#pull-request-checklist) PR format
- [ ] Includes a sample plot to visually illustrate the changes (only for plot-related functions)
- [ ] New features are properly documented (with an example if appropriate)?
- [ ] Includes new or updated tests to cover the new feature
- [ ] Code style  correct (follows pylint and black guidelines)
- [ ] Changes are listed in [changelog](https://github.com/arviz-devs/arviz/blob/main/CHANGELOG.md#v0xx-unreleased)

Following up on @canyon289 's suggestion - this is to avoid problems like https://github.com/arviz-devs/arviz/issues/1560

### CODE REVIEW

**Comment by canyon289** [comment]
I think we should probably disable prints entirely and just use logging. A little outside of this PR but thoughts?

**Review by canyon289 — APPROVED** [review]

**Comment by OriolAbril** [comment]
> One question related I think we should probably disable prints entirely and just use logging. A little outside of the scope of PR but thoughts?

I think we already use only logging and warnings for all our messages. IIUC, the two modified lines that add `file=sys.stdout` are the only print occurrences in the codebase, and they are two tests.

**Comment by ahartikainen** [comment]
Is this PR adding a check that there are no print statements in the codebase?

Why do we need to edit tests? They are hidden by default and when test fails, the printed parts are shown (also -s should show the prints when running locally)

Can we skip checking test folder?

**Comment by MarcoGorelli** [comment]
Sure, done (bit unwieldy without pre-commit, but `-not -path` works)

---

(did I really accidentally open a PR from my `main` branch? oops :facepalm: )

**Pull request merged**
