### PR TITLE
update version number to 0.3.2

### PR DESCRIPTION
**Pull request by ahartikainen**
Small update

### CODE REVIEW

**Comment by aloctavodia** [comment]
shouldn't be just 0.3.2?

**Comment by ahartikainen** [comment]
No, when we update to 0.3.2 it won't install the latest with pip if dev is already installed (is this correct?).

**Comment by canyon289** [comment]
LGTM

**Comment by ahartikainen** [comment]
https://www.python.org/dev/peps/pep-0440/

If we fould make releases then we could add number at the end, but I think we are not releasing dev versions so just `.dev` should be enough.

**Pull request merged**
