### PR TITLE
[WIP] Changed ax.plot to ax.scatter

### PR DESCRIPTION
**Pull request by tattvams**
## Checklist

- [x] Follows [official](https://github.com/arviz-devs/arviz/blob/main/CONTRIBUTING.md#pull-request-checklist) PR format

### CODE REVIEW

**Review by OriolAbril — CHANGES_REQUESTED** [review]
You also need to update the documentation and add a test to ensure the `c` key works properly.

**Comment by OriolAbril** [comment]
@tattvams do you need any help with the tests?

**Review by OriolAbril — APPROVED** [review]
It only needs a rebase to run on the fixed CI but otherwise it is good to merge

**Comment by OriolAbril** [comment]
Hi, sorry. My intention wasn't to close the PR. I rebased the PR to fix CI and be able to merge it. Everything worked properly, but when pushing, only the commits up to main were pushed (rendering the PR with no changes and therefore automatically closing it), after that I got a permission error. I have pushed _all_ the commits I do have locally to https://github.com/arviz-devs/arviz/tree/plot_scatter where you can see it has the right changes and commit authors. Not sure how to fix this though. If I open the PR from this other branch, will commit authorship be maintained when merging? Or will I count as author due to having opened the PR?

**Comment by agustinaarroyuelo** [comment]
We opened and merged #2069 in order to save the changes made in this PR. Please, refer to #2069 to review files changed.

**Pull request closed without merging**
