### PR TITLE
Fix doc build, drop travis-sphinx

### PR DESCRIPTION
**Pull request by ColCarroll**
`travis-sphinx` is a nice project with not much code. The logic here is _almost_ the same as the logic there (they also do a check for cname, that we don't use, and tags on non-master branches).

I'm marking this as a draft: once tests pass, I would like to merge on _my_ fork to make sure nothing gets nuked.

### CODE REVIEW

**Comment by ColCarroll** [comment]
This is ready to merge, but there's some new stylesheet being applied too, so maybe don't merge yet. It:

1. built successfully on my fork: https://colcarroll.github.io/arviz/
2. did not destroy any branches while doing it: https://github.com/ColCarroll/arviz

anyways, check it out: it is thinner than the current version!

**Comment by ColCarroll** [comment]
I found it: there was a `class='body'` being applied on the main content div by `bootstrap-sphinx`, and then `basic.css`, which was being loaded by `bootstrap-sphinx.css` (TIL css can have imports), which set a `max-width` on `body.div`. Which is to say 
1. this is ready to go 
2. i am a frontend ninja now

**Comment by canyon289** [comment]
LGTM, I'll wait 24 hours in case someone else wants to review

**Comment by ColCarroll** [comment]
Restarted current PRs, too.

**Pull request merged**
