### PR TITLE
fix ridgeplot failure for discrete variables

### PR DESCRIPTION
**Pull request by aloctavodia**
Just a quick fix.

### CODE REVIEW

**Comment by aloctavodia** [comment]
@agustinaarroyuelo we may want to revisit this in the future to support quantiles for discrete variables.

**Comment by canyon289** [comment]
Ideally test would be added

**Comment by aloctavodia** [comment]
I was thinking adding tests for discrete variables would be a good fit to @agustinaarroyuelo's GSOC project ;-)

**Comment by canyon289** [comment]
Ok lets keep this open until tests are added. @agustinaarroyuelo if you have questions on how to add tests let me know!

**Comment by aloctavodia** [comment]
This should be merged before the next release, because ridgeplot fails for discrete variables. I will add the test, then we can discuss with Agustina how to improve or increase coverage for discrete and circular variables.

**Comment by canyon289** [comment]
LGTM. Opened an issue for remaining tests https://github.com/arviz-devs/arviz/issues/1191

**Pull request merged**
