### PR TITLE
Added survey report to a new folder in doc folder

### PR DESCRIPTION
**Pull request by roshnaeem**
## Description
We have survey responses only on google forms. It was needed to make a separate formal report of the responses where all ArviZ members can access it. It could help the ArviZ community in the future for documentation development and improvement. 

- I added a new folder in the `/doc` directory named, `GSoD survey`.
- Made a pdf report of the survey responses and placed it in the `GSoD survey` folder.

### CODE REVIEW

**Comment by ColCarroll** [comment]
this is great, thank you! the open ended answers is especially nice.

**Comment by roshnaeem** [comment]
Thanks @ColCarroll :)))

**Comment by OriolAbril** [comment]
could we move that to https://github.com/arviz-devs/GSoD instead?

**Comment by roshnaeem** [comment]
Yeah, sure.

**Pull request merged**
