### PR TITLE
Remove testing dependency on http download for radon dataset

### LINKED ISSUE #1716: Remove testing dependency on http download for radon  dataset
**Describe the bug**
Loading radon dataset is causing network failures in tests. We should remove this dependency anyway since we want our tests to be as isolated as possible.

https://github.com/arviz-devs/arviz/blob/main/arviz/tests/base_tests/test_stats.py#L607

**To Reproduce**
See CI pipeline here
https://dev.azure.com/ArviZ/ArviZ/_build/results?buildId=4434&view=logs&j=e9e5789a-ef7e-54d7-c525-bfdc535bcf80&t=85614d98-b825-523f-f666-d210d5fbfe6e&l=359

Reference PR where we first noticed this https://github.com/arviz-devs/arviz/pull/1710

**Expected behavior**
We test  `def test_loo_pit_multi_lik():` without need for external radon dataset

**Additional context**

### PR DESCRIPTION
**Pull request by utkarsh-maheshwari**
## Description
Modified loo_pit tests to remove dependency on radon dataset. Using modified centered_eight instead.
Closes #1716 

## Checklist

- [ ] Follows [official](https://github.com/arviz-devs/arviz/blob/main/CONTRIBUTING.md#pull-request-checklist) PR format
- [ ] Includes a sample plot to visually illustrate the changes (only for plot-related functions)
- [ ] New features are properly documented (with an example if appropriate)?
- [ ] Includes new or updated tests to cover the new feature
- [ ] Code style  correct (follows pylint and black guidelines)
- [ ] Changes are listed in [changelog](https://github.com/arviz-devs/arviz/blob/main/CHANGELOG.md#v0xx-unreleased)

### CODE REVIEW

**Comment by canyon289** [comment]
This looks fine to me. Im not sure why code coverage is decreasing but testing wise it seems fine. In regards to your other comment I'm not entirely sure what this is testing either but Ive only just glanced at it

**Comment by utkarsh-maheshwari** [comment]
Isn't it safe to merge it?

**Comment by OriolAbril** [comment]
The modified test is failing to trigger this `else` condition: https://app.codecov.io/gh/arviz-devs/arviz/compare/1717/changes#D1L1649. It's nothing to worrying but it should not be difficult to generate synthetic data that ensures this case is tested, I'll try to comment with an option doing this.

**Comment by canyon289** [comment]
> The modified test is failing to trigger this `else` condition: https://app.codecov.io/gh/arviz-devs/arviz/compare/1717/changes#D1L1649. It's nothing to worrying but it should not be difficult to generate synthetic data that ensures this case is tested, I'll try to comment with an option doing this.

@utkarsh-maheshwari if you able to can you see if you can trigger this else case, perhaps with a parameterized test, or a separate test? After that we should be good to for a merge. I know I'm asking for extra work but it certainly will be much appreciated

**Comment by OriolAbril** [comment]
This test checked two things: 1) that loo pit works in all possible cases and that it always returns values between 0 and 1 and 2) that loo_pit works when there are multiple likelihood variables present. The "works in all cases" roughly means having observed data (y) in multiple quantiles of the posterior predictive (y') samples and having both y>y'_i and y<y'_i for all i. The multiple likelihoods test translates into having two variables in `log_likelihood` group, the decoy filled with zeros is great. 

Here is one approach for a synthetic dataset that does all this:

```
rng = np.random.default_rng(0)
pp = rng.standard_normal(size=(4, 100, 10))
qs = np.quantile(pp, np.linspace(0, 1, 10))
obs = qs[np.arange(10), np.arange(10)]
obs[0] *= .9
obs[-1] *= 1.1
idata = az.from_dict(
    posterior_predictive={"y": pp},
    observed_data={"y": obs},
    log_likelihood={"y": -pp**2, "decoy": np.zeros_like(pp)}
)
loo_pit_data = loo_pit(idata, y="y")
assert np.all((loo_pit_data >= 0) & (loo_pit_data <= 1))
```

**Comment by utkarsh-maheshwari** [comment]
> idata = az.from_dict(
    posterior_predictive={"y": pp},
    observed_data={"y": obs},
    log_likelihood={"y": -pp**2, "decoy": np.zeros_like(pp)}
)

@OriolAbril I guess loo_pit need the posterior as well?
https://github.com/arviz-devs/arviz/blob/4d9caca88a9a3b4043062609cb9a401e3f08804d/arviz/stats/stats.py#L1588

**Comment by OriolAbril** [comment]
Oh yes, it should have some random samples.

**Comment by utkarsh-maheshwari** [comment]
@canyon289 I can take this. This PR solves other issues as well.!

**Comment by utkarsh-maheshwari** [comment]
Thanks for helping with the dataset :smile: . @OriolAbril

**Comment by utkarsh-maheshwari** [comment]
I did'nt mentioned the changes in changelog. Thought of doing it after seeing all green

**Comment by OriolAbril** [comment]
Feel free to add them to the changelog in one of your other open PRs

**Pull request merged**
