### PR TITLE
[WIP] make diagnostics work with xarray

### PR DESCRIPTION
**Pull request by aloctavodia**
* The result of any of the 3 functions is a Pandas DataFrame, I was unsure on which data-structure to choose. In some sense this is like the numerical equivalent of a plot.

* This uses `xarray_var_iter`, `selection_to_string` from `plots.plot_utils.py` and thus maybe these functions should be placed inside `utils.xarray_utils.py`

Let me know your thoughts.

### CODE REVIEW

**Comment by aloctavodia** [comment]
btw, test are going to fail, as I did not update them

**Comment by ColCarroll** [comment]
This looks good to me! I wonder if we should perhaps have a dummy `to_xarray` function that works for numpy arrays, if only to use these functions more flexibly.

**Comment by aloctavodia** [comment]
I update summary to make it work with xarray too. Still unsure of what the index of the returned dataframe should be, now is just the name of the variable, thus for a multidimensional variables its name will appear repeated in the index.

**Comment by ahartikainen** [comment]
Do we need to rewite these due to new functions for numpy-->xarray?

**Comment by aloctavodia** [comment]
Right, this PR is totally outdated.

**Comment by ColCarroll** [comment]
I'm taking a look at reviving this - trying to get rid of all the `trace_to_dataframe` calls.

**Pull request closed without merging**
