### PR TITLE
WIP: Adding better error checking to the build script

### PR DESCRIPTION
**Pull request by springcoil**
This is a very quick hacky script extension that I think will work.

### CODE REVIEW

**Comment by springcoil** [comment]
https://github.com/arviz-devs/arviz/issues/416

**Comment by canyon289** [comment]
I'm just curious. What does this change?

**Comment by springcoil** [comment]
My understanding - (I may be completely wrong) is that this will return an error if the docs don't build correctly.

**Comment by canyon289** [comment]
Does this mean the docs build twice?

**Comment by canyon289** [comment]
I actually don't know. I'd have to read the travis ci documentation to understand what's happening.

I trust you, just asking questions to learn from you instead!

**Comment by springcoil** [comment]
Yeah - add in the docs here if you find anything I'll keep looking too :)

**Comment by springcoil** [comment]
It might be superfluous. I've still not really understood travis-sphinx

**Comment by springcoil** [comment]
Fixed - b is unnecessary

**Comment by springcoil** [comment]
What's up with this one?

**Comment by canyon289** [comment]
@springcoil Still invested in this one?

**Comment by springcoil** [comment]
I've not got the time sadly sorry

**Comment by canyon289** [comment]
Worries, I'll close this and if it comes up again we can reopen.

Hope you're able to keep on top of everything else :)

**Pull request closed without merging**
