### PR TITLE
Add docs references to plot_separation docstring

### PR DESCRIPTION
**Pull request by ispedals**
## Description
Added references in the docstring of plot_separation.py file.

- Added link to arviz.InferenceData
- Formatted all parameter references as code
- Documented backend_kwargs
- Add see also section for plot_ppc

Fixes: #1887

### CODE REVIEW

**Comment by ispedals** [comment]
I left the comment

**Comment by roshnaeem** [comment]
@ispedals, let me know if you want to work on any other issue.

**Comment by ispedals** [comment]
@roshnaeem are there any code-related issues I could work on? Otherwise I might do a few more of these documentation ones

**Comment by roshnaeem** [comment]
@ispedals, you can explore the issues and comment on any issue you will like to work on. All of yours PR will be counted in hacktoberfest.

**Pull request merged**
