### PR TITLE
[WIP] Add Dataframe to Inference Data Example to cookbook

### LINKED ISSUE #1490: Add dataframe to InfData examples to cookbook
## Tell us about it
Add dataframe to InfData examples to cookbook

https://arviz-devs.github.io/arviz/getting_started/InferenceDataCookbook.html?highlight=cookbook

```
import pandas as pd
import xarray as xr
import arviz as az
import numpy as np

df = Datasets.Waterbury.to_dataframe()
df["chain"] = 1
df["draw"] = np.arange(len(df), dtype=int)
df = df.set_index(["chain", "draw"])
xdata = xr.Dataset.from_dataframe(df)
idata = az.InferenceData(posterior=xdata)
```

### PR DESCRIPTION
**Pull request by Rishabh261998**
## Description
closes #1490

This is an update on the issue "Add dataframe to InfData examples to cookbook" #1490  I have added the example but there seems to be a problem i.e the created inference object does not have any attributes(eg: created_at, arviz_version). Could you help me tackle this and also provide your feedback. Thanks

### CODE REVIEW

**Comment by Rishabh261998** [comment]
Hi, @OriolAbril can you check the PR and provide anything which I need to update and also the problem which I suggested in the description. Thanks

**Comment by OriolAbril** [comment]
I would use `az.InferenceData(posterior=xdata)` like it is done in the snippet in the issue instead of `convert_to_inference_data`. As we already have Dataset objects, using InferenceData will be more flexible and would allow for example creating multiple groups at once, which `convert...` does not.

Regarding the attributes, do not worry about it. Attributes are added when converting to `xr.Dataset` which all the other examples in the notebook do under the hood. Here however, the Dataset is created manually, so attributes will not be present unless they are manually added.

**Comment by Rishabh261998** [comment]
Thank You for your feedback @OriolAbril, I will change the `convert_to_inference_data` to `InferenceData(posterior=xdata)` and submit a PR.

**Comment by OriolAbril** [comment]
Yes, you can ignore them for now

**Comment by Rishabh261998** [comment]
@OriolAbril is there anything more which I need to update? Thanks

**Comment by OriolAbril** [comment]
Can you rebase with the latest changes from main and then add a bullet point about the change in the changelog?

**Comment by OriolAbril** [comment]
Thanks @Rishabh261998 !

**Comment by Rishabh261998** [comment]
@OriolAbril I was just going through the CHANGELOG.md file and just found out a typo. The first bullet point in the unreleased version links to the PR 1535 but should link to 1518. Thanks

**Comment by OriolAbril** [comment]
Thanks, we can fix this in #1550

**Pull request merged**
