### PR TITLE
[WIP] Changed the stats scale as default to None and made changes accordingly as suggested as per the issue #985

### LINKED ISSUE #985: Integrate ic_scale rcParam
## Tell us about it

`stats.ic_scale` has a default value in rcParams which is not yet used. 

Part of #792 

## Thoughts on implementation

`compare`, `waic` and `loo` should have `None` as default for `ic_scale` and use the default set in rcParams. The implementation should be very similar to
 `stats.information_criterion` integration with `ic` argument

### PR DESCRIPTION
**Pull request by Shashankjain12**
fixes #985

### CODE REVIEW

**Comment by OriolAbril** [comment]
Hi @Shashankjain12 If you enter to the build logs you will see that only [one](https://dev.azure.com/ArviZ/ArviZ/_build/results?buildId=1297&view=logs&j=8b1f4e88-90b9-5fe3-64d9-9b2a3a22d1e4&t=8729fc61-5b5c-512c-a278-229e5112b707) of the [5 jobs](https://dev.azure.com/ArviZ/ArviZ/_build/results?buildId=1297&view=results) is failing, the one called lint. This is due to the code formatting not following the black code style, this should be solved by `black arviz/ examples/` (it's the 3rd point starting from the end in the [pull request checklist](https://github.com/arviz-devs/arviz/blob/master/CONTRIBUTING.md#pull-request-checklist)). 

As to solving the issue, you have now solved the issue only partially. `compare` will now use the value in rcParams, however, there are still functions like `loo`, `waic` and `elpd_plot` that do not yet use the value in rcParams.

**Comment by OriolAbril** [comment]
It looks like you have some issues with your black installation. What does `black --version` print?

**Comment by Shashankjain12** [comment]
@OriolAbril  do we need to create test cases as well manually I guess I had not created any maybe that's the problem?

**Comment by Shashankjain12** [comment]
And black, version is 18.9b0

**Comment by ahartikainen** [comment]
I think you need to update to latest version.

**Comment by Shashankjain12** [comment]
@ahartikainen even after updating black to 19.10b0 no file is changed at all

**Comment by OriolAbril** [comment]
@Shashankjain12 Somehow when you ran black, 32 extra files were reformatted (this is why now it says that this PR modifies 33 files), and they were reformatted in a way that the files cannot be parsed in python 3.5 (hence the build failure). 

Somehow an old version of black is formatting the code, could there be 2 different installations? Otherwise you can try to code from within docker which will have the correct packages. We have a guide [here](https://github.com/arviz-devs/arviz/blob/master/CONTRIBUTING.md#developing-in-docker) that should help you.

**Comment by Shashankjain12** [comment]
So @OriolAbril do i need to delete my repo and try that again in order to contribute to this?

**Comment by OriolAbril** [comment]
You should not have to delete the whole repository, it looks like it only has to do with black. 

Try uninstalling and reinstalling again just in case.

And if it does not work, using docker should allow to code from your computer on the same repo you already have but from within a container that has different programs available (inside which black should work properly)

**Comment by ahartikainen** [comment]
Hi @Shashankjain12 how have you installed your python? Are you using conda?

For example I use this workflow (with miniconda (+ cmder on Windows)) --> Use conda environment

https://pystan.readthedocs.io/en/latest/installation_beginner.html
https://pystan.readthedocs.io/en/latest/windows.html (<< conda stuff works for other OS too)

https://docs.conda.io/en/latest/miniconda.html <<- I use local folder e.g. "/home/miniconda3" and I add the conda on the PATH at installation step
https://cmder.net/

**Comment by OriolAbril** [comment]
@Shashankjain12 The changes in `stats.py` look great. Only `plot_elpd` needs to be updated now.

**Comment by Shashankjain12** [comment]
what is ```plot_elpd``` @OriolAbril ?

**Comment by OriolAbril** [comment]
[`plot_elpd`](https://arviz-devs.github.io/arviz/generated/arviz.plot_elpd.html#arviz.plot_elpd)

**Comment by Shashankjain12** [comment]
Ok sure thanks I will  update that :+1:

**Comment by Shashankjain12** [comment]
Why is this showing error now @OriolAbril I had not changed any file ?

**Comment by Shashankjain12** [comment]
Done @OriolAbril :+1:

**Pull request merged**
