### PR TITLE
Rename N_effective to S_effective

### PR DESCRIPTION
**Pull request by canyon289**
Trying to make it more clear to users and newcomers to Bayesian methodology what calculation is being done and where to look for further reference
 
Review requested more for the idea of the change, and less so the code.

I can add deprecation or rename warning to `n_effective` to make this a non breaking change

### CODE REVIEW

**Comment by ahartikainen** [comment]
hmm, Should we then also move to split calculations

**Comment by canyon289** [comment]
@ahartikainen On your question you and @aloctavodia are much better experts on this than I am.

The perspective I have is that I was very very confused when trying to learn how this method really worked because the naming, and the reference, did not match the code.

Whether we should move to split calculations though I'm not sure! Happy to take suggestion

**Code Note**
Rebased this PR on top of the pytest_pin branch

**Comment by junpenglao** [comment]
I think we should move to split calculations.
cc @avehtari

**Comment by ahartikainen** [comment]
I updated Rhat to use split function. Not sure about the Seff.

**Comment by junpenglao** [comment]
@canyon289 maybe we can do the same - renaming it to ESS, and wait for Stan to update to split calculation.

**Comment by avehtari** [comment]
The current best reference for what is currently used in Stan, is Stan manual. See sections 15.3 and 15.4
https://mc-stan.org/docs/2_18/reference-manual/notation-for-samples-chains-and-draws.html
https://mc-stan.org/docs/2_18/reference-manual/effective-sample-size-section.html

Rhat and ESS case study is the best reference what is planned for the future. Section 2 is review. Section 3 is new material. Sections 3.10-3.12 provide explicit proposal for changes. This case study will change to a paper and vignette during the spring.

**Pull request merged**
