### PR TITLE
add clip_on for n_eff

### PR DESCRIPTION
**Pull request by ahartikainen**
Simple fix

### CODE REVIEW

**Comment by ahartikainen** [comment]
Before 

image

After

image

After

image

After

image


ps. What is going on with the order here? After each plot I have restarted Notebook and imported eight_schools with arviz_.load_...? It randomly changes the order. Dataset order is static.

**Comment by ColCarroll** [comment]
While you're here, do you want to add the fix in `plot_rhat`, too?

**Comment by ahartikainen** [comment]
For plot_forest? It will be trickier.

**Comment by ColCarroll** [comment]
Forgot the axes were set strangely - thanks for fixing!

**Pull request merged**
