### PR TITLE
Fix extra argument behavior

### PR DESCRIPTION
**Pull request by canyon289**
Same question as before though! Why force people to use keyword argument?

### CODE REVIEW

**Comment by ColCarroll** [comment]
Cool - looks like this change turned up a few legitimate bugs like the one you pointed out in #188: 

```
************* Module arviz.tests.test_xarray_utils
arviz/tests/test_xarray_utils.py:111:15: E1121: Too many positional arguments for function call (too-many-function-args)
************* Module arviz.plots.densityplot
arviz/plots/densityplot.py:64:20: E1121: Too many positional arguments for function call (too-many-function-args)
************* Module arviz.plots.forestplot
arviz/plots/forestplot.py:161:21: E1121: Too many positional arguments for function call (too-many-function-args)
```

**Comment by ColCarroll** [comment]
Oh, and I wanted a positional argument so the library would be more explicit and readable. It is easy to remove in the future, but hard to add back in. If it gets too annoying, we can remove!

**Comment by ahartikainen** [comment]
It will make usage more robust. Especially important for plotting library where users have used other libs before (e.g mpl)

**Comment by ahartikainen** [comment]
especially important if we go with multiple backends

**Comment by canyon289** [comment]
> Oh, and I wanted a positional argument so the library would be more explicit and readable. It is easy > to remove in the future, but hard to add back in. If it gets too annoying, we can remove!

You mean you wanted to a *keyword* argument?

Makes sense and I agree, by forcing people to use keywords itll make it way easier to make changes without breaking peoples code later.

**Pull request merged**
