### PR TITLE
add analytics

### PR DESCRIPTION
**Pull request by OriolAbril**
## Checklist

- [ ] Follows [official](https://github.com/arviz-devs/arviz/blob/main/CONTRIBUTING.md#pull-request-checklist) PR format
- [ ] Includes a sample plot to visually illustrate the changes (only for plot-related functions)
- [ ] New features are properly documented (with an example if appropriate)?
- [ ] Includes new or updated tests to cover the new feature
- [ ] Code style  correct (follows pylint and black guidelines)
- [ ] Changes are listed in [changelog](https://github.com/arviz-devs/arviz/blob/main/CHANGELOG.md#v0xx-unreleased)

### CODE REVIEW

**Comment by OriolAbril** [comment]
Turns out we depend on https://github.com/pydata/pydata-sphinx-theme/pull/387 for the `G-` code we have to work

**Comment by FabioRosado** [comment]
Hello @OriolAbril  hope you don't mind me commenting here. I've added the tests to the PR so hopefully it will get merged and released soon(ish)

My workaround until the PR is merged is to put the Google analytics script inside our `_template/layout.html` until we get it merged 😄  Hope this helps

**Comment by OriolAbril** [comment]
Thanks for commenting! I'll do that if I have time, I first have to do some other urgent work related to season of docs.

**Comment by FabioRosado** [comment]
Would you be open if I submit a quick PR for it? If you agree of course

**Comment by OriolAbril** [comment]
That would be amazing! :heart:

**Pull request merged**
