### PR TITLE
add sample_stats for PyStan

### PR DESCRIPTION
**Pull request by ahartikainen**
Add sample_stats for PyStan.

### CODE REVIEW

**Comment by ahartikainen** [comment]
I added `lp__` to here. Is this correct thing to do or should it be inside posterior?

**Comment by ColCarroll** [comment]
Looks good to me -- can merge when tests pass.

Is `lp__` the log probability?  Maybe we should rename it to `log_probability` - there is an open PR to add that to PyMC3 where it is called `logp`(https://github.com/pymc-devs/pymc3/pull/3134), and I think sampler stats is the right place for it. I'll add a PR to the pymc3 converter with whatever name you prefer.

**Comment by ColCarroll** [comment]
I really like including that in sampler stats. Maybe we call it `log_density` since that _technically_ covers both cases?

**Comment by junpenglao** [comment]
log_density could be confusing, I dont mind keeping it as `lp__` actually - it minimized the name changes across in Stan, and we dont have it yet anyway in pymc3.

**Comment by ahartikainen** [comment]
I guess we can keep it as is (I stripped __ from the end)

**Pull request merged**
