### PR TITLE
WIP Import coords and dims from pymc3

### PR DESCRIPTION
**Pull request by aseyboldt**
*Depends on https://github.com/pymc-devs/pymc3/pull/3551 *
This allows arviz to read dims and coords from pymc3 when they are defined.

### CODE REVIEW

**Comment by canyon289** [comment]
This looks great! Is it still in WIP and or do we need to add tests?

**Comment by ahartikainen** [comment]
Is this ready (I would like to get this in for the next release)

**Comment by canyon289** [comment]
Checking in on old PRs. Any possibility of bringing this over the line or should we close?

**Comment by OriolAbril** [comment]
I think this depends on a PR to PyMC3 that just got reactivated. We should probably revisit after https://github.com/pymc-devs/pymc3/pull/3551 has been merged and see if it would require any release magic/monkeypatching... cc @AlexAndorra @michaelosthege 

If interesting, I can rebase the PR (I am quite up to date with changes in io_pymc3 and should not break any of the new changes while rebasing)

**Comment by AlexAndorra** [comment]
Indeed, I'm planning to review the PyMC PR in the coming days -- will keep you posted 😉 
We're trying to merge the PR to have it in 3.9, so it should be resolved quite quickly.

**Comment by michaelosthege** [comment]
I resolved the conflicts in #1228. Testing with the PyMC3 PR branch now…
This PR can be closed.

**Pull request closed without merging**
