### PR TITLE
[WIP] Cleaning up TFP io

### PR DESCRIPTION
**Pull request by percygautam**
Solves issue #812 . The following changes are made:

- Migration of TF1 to TF2.

### CODE REVIEW

**Comment by percygautam** [comment]
I am still working on issue #812 . This is to keep my work reviewed.

**Comment by percygautam** [comment]
@OriolAbril Okay I'll do that.

**Comment by percygautam** [comment]
@OriolAbril I am getting confused over some things. Like for example, in the below example:
```
        if isinstance(self.observed, self.tf.Tensor):
            with self.tf.Session() as sess:
                vals = sess.run(self.observed, feed_dict=self.feed_dict)
        else:
            vals = self.observed
```
I need to know about the data self.observed that is passed as fetches to `session.run()` so as to use it in created function in TF2. Can you please provide me with some example so as to understand the process?
Meanwhile, I'd try to get myself more familiar with the data structures used?

**Comment by OriolAbril** [comment]
@percygautam I have never used TF2, I am afraid I cannot help with this, sorry.

**Comment by percygautam** [comment]
@OriolAbril Can you refer me to someone with experience? I'll really like to work on it.

**Comment by canyon289** [comment]
@percygautam I would take a look at PyMC4 implementation as it works in TF2. I myself am not familiar with Tensorflow 2 well enough to make a specific recommendation but I'm thinking that perhaps their reference implementation might help!

**Comment by percygautam** [comment]
Thank you @canyon289 . I'll refer to it and do the changes soon.

**Comment by canyon289** [comment]
Checking in on old PRs. Any possibility of bringing this over the line or should we close?

**Comment by percygautam** [comment]
I think we should close this one. I don't have enough experience with TF yet.

**Comment by canyon289** [comment]
Thanks @percygautam. Feel free to open whenever you feel ready

**Pull request closed without merging**
