### PR TITLE
support PyStan version < 2.18

### PR DESCRIPTION
**Pull request by ahartikainen**
This will first try to extract with parameters and  `permuted=False`. In older versions, it will return numpy.array and in later versions a dictionary. If a dictionary is not seen, it will extract again, but permuted=True and then goes to reorder permutation.

Also added `lp` back to sample_params, it went missing after the "rebase".

### CODE REVIEW

**Comment by ColCarroll** [comment]
LGTM -- travis failures are:

```
************* Module arviz.utils.xarray_utils
arviz/utils/xarray_utils.py:310:0: C0301: Line too long (104/100) (line-too-long)
arviz/utils/xarray_utils.py:301:8: C0103: Variable name "lp" doesn't conform to snake_case naming style (invalid-name)
arviz/utils/xarray_utils.py:310:12: C0103: Variable name "lp" doesn't conform to snake_case naming style (invalid-name)
arviz/utils/xarray_utils.py:313:12: C0103: Variable name "lp" doesn't conform to snake_case naming style (invalid-name)
arviz/utils/xarray_utils.py:315:15: W0612: Unused variable 'sampler_dict' (unused-variable)
```

**Comment by ahartikainen** [comment]
I will still test on my local machine, after that we can merge.

**Comment by ahartikainen** [comment]
Tested with PyStan 2.18 and PyStan 2.17.1. Works now with both of them.

This means that we can start to use `pip install pystan` in testing.

I will add a change for that too.

**Comment by ColCarroll** [comment]
Cool!

**Pull request merged**
