### PR TITLE
Doc improvements

### PR DESCRIPTION
**Pull request by OriolAbril**
## Description
This PR adds several new features to docs. Some of them are a not very well documented so I'll try to add this to the developer guide so we can make the most of these improvements.

### Using see also
The see also section can also be used and links are generated automatically by sphinx. See [`compare` for one example](https://oriolabril.github.io/arviz/generated/arviz.compare.html#arviz.compare). ~We have to modify the css file to change the color, otherwise it is hardly readable.~ Any help would be greatly appreciated.

### Referencing methods in other libraries
For now, xarray and pymc3 are configured to make it easy to reference their docs. This is possible thanks to [intersphinx](https://docs.readthedocs.io/en/stable/guides/intersphinx.html). Therefore, rst code such as:

    :func:`pymc3:pymc3.sampling.sample`
    :meth:`xarray.Dataset.sel <xarray:xarray.Dataset.sel>`  # example of modifying link text

Will directly link to the corresponding docs, see [`from_pymc3`](https://oriolabril.github.io/arviz/generated/arviz.from_pymc3.html#arviz.from_pymc3) and [`InferenceData.sel`](https://oriolabril.github.io/arviz/generated/arviz.InferenceData.sel.html#arviz.InferenceData.sel). The initial part is quite tricky, depending on what is referenced it has to be one or another key. The accepted keys can be found [here](https://github.com/sphinx-doc/sphinx/blob/685e3fdb49c42b464e09ec955e1033e2a8729fff/sphinx/domains/python.py#L845-L881), however in some cases it can be hard to guess. In such cases, the [sphobjinv](https://sphobjinv.readthedocs.io/en/latest/) package can come in handy. It can search the documentation for us and return the interesting objects to tag:

```
$ sphobjinv suggest -t 90 -u https://docs.pymc.io/objects.inv "sampling.sample"
 
Remote inventory found.
 
:py:function:`pymc3.sampling.sample`
:py:function:`pymc3.sampling.sample_posterior_predictive`
:py:function:`pymc3.sampling.sample_posterior_predictive_w`
:py:function:`pymc3.sampling.sample_ppc`
:py:function:`pymc3.sampling.sample_ppc_w`
:py:function:`pymc3.sampling.sample_prior_predictive`
:std:label:`/api/inference.rst#pymc3.sampling.sample`
:std:label:`/api/inference.rst#pymc3.sampling.sample_posterior_predictive`
:std:label:`/api/inference.rst#pymc3.sampling.sample_posterior_predictive_w`
:std:label:`/api/inference.rst#pymc3.sampling.sample_ppc`
:std:label:`/api/inference.rst#pymc3.sampling.sample_ppc_w`
:std:label:`/api/inference.rst#pymc3.sampling.sample_prior_predictive`
```

The codes still have to be updated from `:py:function:` to `:py:func:` to follow match the accepted keys, see link above.

### Referencing ArviZ functions
Same thing as above can be used: `:py:func:` and similar keywords.

### Other
Several formatting fixes to reduce warnings and make sure all plots in docstring are correctly generated and updating from `m2r` to `recommonmark` to convert markdown to rst. ~Now everything should be sphinx3 compatible.~ Everything is now sphinx3 compatible.

## Checklist

- [x] Follows [official](https://github.com/arviz-devs/arviz/blob/master/CONTRIBUTING.md#pull-request-checklist) PR format
- [x] New features documented in the developer guide
- [x] Code style  correct (follows pylint and black guidelines)
- [x] Changes are listed in [changelog](https://github.com/arviz-devs/arviz/blob/master/CHANGELOG.md#v0xx-unreleased)

### CODE REVIEW

**Comment by AlexAndorra** [comment]
This looks really great, thanks @OriolAbril ! 
I'd be curious to work on it with you if you need help -- not before next week though.

Disclaimer: I'm close to a noob on doc generation, but this seems like a good time to understand how this works on ArviZ -- plus, I'd like to do something similar on PyMC3, where the stats docs would directly redirect to ArviZ to avoid inconsistencies.

**Comment by OriolAbril** [comment]
Great! Thanks for the help! I can try to help with PyMC3 docs too. 

Do you want to change anything else in the configuration? Otherwise we can merge and divide adding the references into several PRs

**Comment by AlexAndorra** [comment]
TBH I don't really now what's the best option yet 😅
Maybe the most efficient would be to have a video call and talk about it?

Le ven. 15 mai 2020 à 21:55, Oriol Abril <notifications@github.com> a
écrit :

**Comment by canyon289** [comment]
I vote merging.

**Comment by canyon289** [comment]
Alright its been a day. Merging this. We can figure out cross docs later! Thanks @OriolAbril

**Pull request merged**
