### PR TITLE
Fix warning and docstring for generate_dims_coords.

### PR DESCRIPTION
**Pull request by rpgoldman**

### CODE REVIEW

**Comment by rpgoldman** [comment]
👌 will do

--  
Robert P. Goldman

**Comment by canyon289** [comment]
@rpgoldman we're looking to cut a release soon. If you want to get this in let us know so we can wait for the fix to include it

**Comment by rpgoldman** [comment]
OK, I'll see if I can get it done this afternoon.

**Comment by rpgoldman** [comment]
OK, I think I have done everything.  If this passes the CI, now that I have fixed the linting, please merge it.  I strongly suggest squash merging -- no one reading the history needs to know I forgot to run `black` before pushing!

**Comment by OriolAbril** [comment]
LGTM, thanks!

Don't worry about the commit history, all PRs are squash merged in ArviZ.

**Comment by ahartikainen** [comment]
LGTM

**Comment by ahartikainen** [comment]
Thanks for the PR!

**Pull request merged**
