### PR TITLE
Fix numpy multidimensional indexing

### PR DESCRIPTION
**Pull request by canyon289**
Regarding https://github.com/arviz-devs/arviz/issues/271 I fixed the code paths that raised FutureWarnings from which I could detect through testing.

@ahartikainen mentioned there's a couple of cases in stats.py but I'm *not* able to see them 

If there are cases left I would be happy with any of the following (or any suggestions really)
* Tell me where they are so I can edit them
* Tell me what method they are in so I can write more tests
* Update this PR directly

### CODE REVIEW

**Comment by ahartikainen** [comment]
High, I can test this before merge

**Comment by canyon289** [comment]
Hey @ahartikainen 
What does the word high mean in the context above?

**Comment by canyon289** [comment]
Also misworded my message above. I am unable to see the places in stats.py where multidimensional indexing is being used, and I wasn't able to detect them by running tests.

**Comment by ahartikainen** [comment]
Haha, it should be hi! So autocorrect 😆

**Comment by ahartikainen** [comment]
Yes, this looks good. I will merge it.

Other warnings are coming from numpy (mkl_fft).

**Pull request merged**
