### PR TITLE
Fix io_cmdstanpy error when importing a fit with vector parameter of length 1

### PR DESCRIPTION
**Pull request by jburos**
## Description

This addresses #1646, which causes an error when importing from cmdstanpy, particularly regarding the distinction between a scalar and vector of length 1. My guess is that this is legacy code from previous versions where the dimension or type had to be inferred rather than known. 

## Checklist

- [x] Follows [official](https://github.com/arviz-devs/arviz/blob/main/CONTRIBUTING.md#pull-request-checklist) PR format
- [x] Code style correct (follows pylint and black guidelines)
- [x] Changes are listed in [changelog](https://github.com/arviz-devs/arviz/blob/main/CHANGELOG.md#v0xx-unreleased)

### CODE REVIEW

**Comment by ahartikainen** [comment]
What cmdstanpy version causes the error?

**Comment by ahartikainen** [comment]
@OriolAbril why did we have this special case originally?

**Comment by OriolAbril** [comment]
Not sure, looking at the issue discussion I previously guessed it was to properly distinguish between scalar and 1d vector, but I am not sure those two cases can be distinguished in old cmdstanpy cases. I think we should merge this and add a new test on cmdstanpy data that checks scalar and 1d vector data (here or in a follow-up PR)

**Comment by OriolAbril** [comment]
Thanks @jburos! 

As a PSA and for future me, I think new cmdstanpy should be prioritized over old ones (that we have tested work correctly with old ArviZ versions also). Now going to the issue which I won't close yet to signal a test is needed for this case

**Pull request merged**
