### PR TITLE
Automatically take coords and dims from PyMC3 model

### PR DESCRIPTION
**Pull request by michaelosthege**
This PR supersedes #757 (I can't push to Adrians branch) and resolves conflicts with master. (Rebases over almost a year of commits!)

When https://github.com/pymc-devs/pymc3/pull/3551 is merged, this PR enables ArviZ to automatically take `coords` and `dims` from the PyMC3 model.

### CODE REVIEW

**Comment by OriolAbril** [comment]
Do you prefer to wait until PR is merged in PyMC3 and add tests here or merge this now and add test in follow-up PR once pymc3 one has been merged?

**Comment by AlexAndorra** [comment]
I think we can wait and tests here -- the PyMC PR should be ready soon

**Comment by OriolAbril** [comment]
is the new functionality only for dims or for coords too? 

LGTM, I think we can merge like this and open an issue so we remember to extend the test to coords too.

**Comment by michaelosthege** [comment]
@OriolAbril the way how I understand it is that dims/coords go hand in hand. The keys are the dims, the values to coords.

**Comment by OriolAbril** [comment]
Ohh, I read too past and missed the `pm.Model(coords=coords)`

**Comment by kyleabeauchamp** [comment]
I think the current pymc3  <> arviz coords integration is broken in the current pymc3 release because it is using an arviz version that does not have this code present.

See https://github.com/pymc-devs/pymc3/pull/3977 and https://github.com/pymc-devs/pymc3/issues/3976 for details

**Comment by michaelosthege** [comment]
> I think the current pymc3  <> arviz coords integration is broken in the current pymc3 release because it is using an arviz version that does not have this code present.
> See pymc-devs/pymc3#3977 and pymc-devs/pymc3#3976 for details

Broken in the sense that the feature is not there, right? ArviZ 0.8.3 doesn't automatically take the coords, because this PR came in after 0.8.3.
The PyMC3 example notebooks (which are not yet rendered for https://docs.pymc.io) were run with ArviZ master, which may cause some confusion.

The real issue here is that we're still sitting on some technical debt in both projects when it comes to releasing & doc-building.

**Pull request merged**
