### PR TITLE
Run tests without numba

### PR DESCRIPTION
**Pull request by ahartikainen**
By following recommendation in https://stackoverflow.com/questions/26875191/analyzing-coverage-of-numba-wrapped-functions

Basically it goes to numba, but returns the normal function.

### CODE REVIEW

**Comment by canyon289** [comment]
Ah, I know what's going on, this seems to break the test I made yesterday for the decorator test.

**Comment by ahartikainen** [comment]
No, that last commit was my fault. Everything before last commit works. I'm just trying to see if there would be a way return results from wrapper and function :D

**Comment by canyon289** [comment]
Ah ok, I'll leave you to it! Thanks for the fix

**Comment by ahartikainen** [comment]
I think this will work.

**Comment by canyon289** [comment]
That last one is a good idea!

**Comment by ahartikainen** [comment]
Oh wait, I have even better

**Comment by ahartikainen** [comment]
I was fooled by the lambda + comma

**Pull request merged**
