### PR TITLE
upload updated mypy.ini if needed

### PR DESCRIPTION
**Pull request by ahartikainen**
## Checklist

- [ ] Follows [official](https://github.com/arviz-devs/arviz/blob/main/CONTRIBUTING.md#pull-request-checklist) PR format
- [ ] Includes a sample plot to visually illustrate the changes (only for plot-related functions)
- [ ] New features are properly documented (with an example if appropriate)?
- [ ] Includes new or updated tests to cover the new feature
- [ ] Code style  correct (follows pylint and black guidelines)
- [ ] Changes are listed in [changelog](https://github.com/arviz-devs/arviz/blob/main/CHANGELOG.md#v0xx-unreleased)

### CODE REVIEW

**Comment by ahartikainen** [comment]
Hey, it works. If someone else could confirm this too I can remove those non-needed commits and we can merge this.

**Comment by canyon289** [comment]
So I read this but I dont really get what it does and am confused that you say it works but CI is failing?

For specifica feedback, can we add a comment to yml file explaining what this thing is, even one line helps
And in regards to CI if its failing how do you know it works?

**Comment by OriolAbril** [comment]
We recently added mypy and typing copilot to CI. mypy checks that the code does not incur in any type errors, which sounds great, however, many parts of our codebase and many of our dependencies do not use type hints everywhere (or at all). Therefore, mypy check relies on a very long and specific `mypy.ini` file that ensures we make the most of the type hints available without getting any errors due to the missing type hints. typing copilot is what takes care of this file. typing copilot was first used to generate a base `mypy.ini` file, and now it is also executed on CI to check if we can "tighten" this file, that is, remove some of the ignores because we our our dependencies added type hints. If we can tighten, typing copilot _will fail the CI job_! This is what is happening now, ci is failing because we can improve our mypy.ini.

The improvement Ari is adding with this PR is that now, whenever typing copilot fails ci, azure will rerun typing copilot, but not as a check, as mypy.ini generator and upload the improved mypy.ini as an artifact. Thus, "fixing" the failing CI will become downloading the updated mypy.ini from azure and adding it to the repo.

**Comment by OriolAbril** [comment]
I can confirm that the mypy.ini is uploaded and looks great, thanks for this @ahartikainen

**Comment by ahartikainen** [comment]
Do we add a mention about updating mypy.ini in #1587 or here?

**Comment by OriolAbril** [comment]
I would do it at #1587, still trying to decide how to organize the doc, but I think we should probably have a section about CI

**Review by OriolAbril — APPROVED** [review]

**Comment by obi1kenobi** [comment]
Very cool!

**Pull request merged**
