### PR TITLE
Fix test errors

### PR DESCRIPTION
**Pull request by canyon289**
Hopefully fixes (oddly) failing master branch

https://travis-ci.org/arviz-devs/arviz/builds/456930803

### CODE REVIEW

**Comment by ahartikainen** [comment]
Is this ready?

**Comment by canyon289** [comment]
Yes, if there's no feedback we can merge

**Comment by ColCarroll** [comment]
Looks good to me! `module` fixtures run once per test suite?

**Comment by canyon289** [comment]
Should be once per module, so if a fixture is used in two python files it runs one per. Session is once per test run.

**Pull request merged**
