### PR TITLE
Azure pipelines

### PR DESCRIPTION
**Pull request by canyon289**
Testing out Azure Pipelines

### CODE REVIEW

**Comment by canyon289** [comment]
Is anyone else able to see the CI details of the azure pipeline? I want to be sure they're accessible to everyone

**Comment by kyleabeauchamp** [comment]
yes

**Comment by canyon289** [comment]
Ready for review. I'm thinking we side by side this with TravisCI for a while to see how it all works out.

After that if we're ready we can take down Travis Unit Test and Lint. I haven't figured out ghp-import for the Sphinx Docs yet, but talking to the Pandas team they still use TravisCI for their docs so I guess I can be lazy and leave it be for a while. Happy to hear thoughts

**Comment by ahartikainen** [comment]
LGTM

**Pull request merged**
