### PR TITLE
Fix label guide rendering [docs]

### PR DESCRIPTION
**Pull request by nk3843**
Hi ,

This resolves these two issues.

Please review.

As for the changes themselves, there are two to be done:

Move the ipython directive https://github.com/arviz-devs/arviz/blob/main/doc/source/user_guide/label_guide.rst#L14 a few lines down. It should be right before the code (like in the rest of examples) instead of having a section title in the between.
Fix the see also directive in https://github.com/arviz-devs/arviz/blob/main/doc/source/user_guide/label_guide.rst#L58. There should be no dash and it should be indented 3 spaces.

Best,
Nikhil

## Checklist

- [ ] Follows [official](https://github.com/arviz-devs/arviz/blob/main/CONTRIBUTING.md#pull-request-checklist) PR format
- [ ] Includes a sample plot to visually illustrate the changes (only for plot-related functions)
- [ ] New features are properly documented (with an example if appropriate)?
- [ ] Includes new or updated tests to cover the new feature
- [ ] Code style  correct (follows pylint and black guidelines)
- [ ] Changes are listed in [changelog](https://github.com/arviz-devs/arviz/blob/main/CHANGELOG.md#v0xx-unreleased)

### CODE REVIEW

**Comment by canyon289** [comment]
Hi @nk3843. Im going to close and reopen this just to see if I can get Azure to start a CI build!

**Comment by canyon289** [comment]
Looks like it worked. Thank you for the contribution @nk3843

**Comment by canyon289** [comment]
This LGTM! Will leave open for a bit in case anyone else wants to comment

**Comment by canyon289** [comment]
Thanks @nk3843. Merging

**Comment by nk3843** [comment]
Glad to be of help! @canyon289

**Pull request merged**
