### PR TITLE
Revert despine on bokeh

### PR DESCRIPTION
**Pull request by ahartikainen**
## Description

Remove despine from bokeh violinplot. Each ax (bokeh.figure) is its own object, so we can rearrange and handle each ax individually.

Despining is confusing when user uses other than default for figure location.

## Checklist

- [ ] Follows [official](https://github.com/arviz-devs/arviz/blob/master/CONTRIBUTING.md#pull-request-checklist) PR format
- [ ] Includes a sample plot to visually illustrate the changes (only for plot-related functions)
- [ ] New features are properly documented (with an example if appropriate)?
- [ ] Includes new or updated tests to cover the new feature
- [ ] Code style  correct (follows pylint and black guidelines)
- [ ] Changes are listed in [changelog](https://github.com/arviz-devs/arviz/blob/master/CHANGELOG.md#v0xx-unreleased)

### CODE REVIEW

**Comment by aloctavodia** [comment]
Currently subplots in violinplot are not independent, if you move one the other will moves too.

**Comment by ahartikainen** [comment]
Sure, that is by design. But the subplot order is independent. The default is grid, but there is also possibility to use rectangular (and also do it manually)

**Comment by aloctavodia** [comment]
ok, could we keep despine as optional or could we have it activated by default when "sharey=True"?

**Comment by ahartikainen** [comment]
sharey is doing different thing on bokeh.

We could have some kw if we want

**Review by aloctavodia — APPROVED** [review]
LGTM!

**Pull request merged**
