### PR TITLE
Add verbiage for unassigning issue tickets

### PR DESCRIPTION
**Pull request by canyon289**
Add a policy so we can unassign people from issue tickets without having to feel bad about it as the expectations are clear and written unambiguously for all

### CODE REVIEW

**Comment by ColCarroll** [comment]
I wonder if there's a bot for this? It'd be cool to automatically ping after 12 days, then unassign at 14 with a reasonable message (feel free to pick it back up if you have time!). 

I approve of this, but will wait if others have comments.

**Comment by AlexAndorra** [comment]
+1 for @ColCarroll's suggestions -- if such a bot exists 🤔

**Comment by aloctavodia** [comment]
maybe this is what we want https://github.com/probot/reminders?

**Comment by canyon289** [comment]
We want a conditional robot though right? Like that same robot but with this stale addon?
https://github.com/probot/stale

**Pull request merged**
