### PR TITLE
Added significant digits formatter for rope values

### PR DESCRIPTION
**Pull request by MgeeeeK**
## Description

Added significant digits formatter for rope values. To fix [#1561](https://github.com/arviz-devs/arviz/issues/1561)

## Checklist

- [x] Follows [official](https://github.com/arviz-devs/arviz/blob/main/CONTRIBUTING.md#pull-request-checklist) PR format
- [x] Code style  correct (follows pylint and black guidelines)
- [x] Changes are listed in [changelog](https://github.com/arviz-devs/arviz/blob/main/CHANGELOG.md#v0xx-unreleased)

### CODE REVIEW

**Comment by MgeeeeK** [comment]
Hi @OriolAbril can you take a look

**Review by OriolAbril — COMMENTED** [review]
Looks great, thanks! You have to run black and add it to the changelog, then we can merge it.

**Comment by OriolAbril** [comment]
What version of black do you have? It should not be modifying any unmodified file  🤔

**Comment by MgeeeeK** [comment]
I was having same doubt looks like my package is outdated (its `19.3b0` installed using conda). Will update and push again.

**Comment by OriolAbril** [comment]
You may have to undo the latest commit for this to work. Have you ever done interactive rebase?

**Review by OriolAbril — APPROVED** [review]

**Pull request merged**
