### PR TITLE
Use arviz_example_data submodule

### PR DESCRIPTION
**Pull request by sethaxen**
## Description

Replaces stored example data with arviz_example_data based on https://github.com/arviz-devs/arviz_example_data/pull/6. Note: this should not be merged until that PR is merged!

## Checklist

- [x] Follows [official](https://github.com/arviz-devs/arviz/blob/main/CONTRIBUTING.md#pull-request-checklist) PR format
- [ ] New features are properly documented (with an example if appropriate)?
- [x] Includes new or updated tests to cover the new feature
- [x] Code style  correct (follows pylint and black guidelines)
- [x] Changes are listed in [changelog](https://github.com/arviz-devs/arviz/blob/main/CHANGELOG.md#v0xx-unreleased)

----
:books: Documentation preview :books:: https://arviz--2096.org.readthedocs.build/en/2096/

### CODE REVIEW

**Comment by OriolAbril** [comment]
The azure errors seem related to this: https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#checkout. IIUC, by default, submodules are not cloned, but I don't completely understand how to get them to clone

**Comment by sethaxen** [comment]
Thanks! Still some links to iron out for specific builds, but it seems to work for some of them now.

**Comment by OriolAbril** [comment]
Looks great already, let's merge https://github.com/arviz-devs/arviz_example_data/pull/6 to make it easier, thanks for getting this started

**Comment by sethaxen** [comment]
@OriolAbril do you know how to tell black to skip the `example_data` directory? I tried to do it with pylintrc but it seems was not successful.

**Comment by OriolAbril** [comment]
It should be done from pyproject.toml. I think if you add something like to the `tool.black` section:

```
extend_exclude = 'example_data'
```

ref: https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#configuration-format

**Comment by sethaxen** [comment]
The remaining errors seem to also occur on main and be unrelated to this PR. This is now ready for review.

**Review by OriolAbril — APPROVED** [review]

**Comment by OriolAbril** [comment]
Thanks! 

I also want to put on record that out of the last 4 PRs we have merged, 3 of them recuded the number of code lines while improving or maintaining functionality! 🎉

**Pull request merged**
