### PR TITLE
Modify ci script to only deploy docs once

### PR DESCRIPTION
**Pull request by canyon289**
Trying out this one 
https://github.com/arviz-devs/arviz/issues/153

If there's a better way let me know so I can learn!

### CODE REVIEW

**Comment by ColCarroll** [comment]
Straightforward and easy to understand. We can check if the image below reduces to only 1 commit when merging!

image

**Comment by canyon289** [comment]
Where are you taking the screenshot? I'm looking at the gh-pages branch but can't seem to see the commits on Github

**Comment by ColCarroll** [comment]
er, that's just on my github feed, which might be a new version. I think I "watch" the repo.  Looks like this didn't fix it!  You merged two commits, and this pushed 6 to the docs...

image

**Comment by canyon289** [comment]
Dang, 
I'll keep looking into it

**Comment by canyon289** [comment]
So I found a stackoverflow answer that may help
It says this is possible
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then then travis-sphinx deploy; fi

I can make the change but I really don't know of any other test than to have you merge a PR and then see what happens.

What do you think? Is there a better alternative?

https://stackoverflow.com/questions/20617600/travis-special-requirements-for-each-python-version

**Comment by canyon289** [comment]
Also it seems Tornados CI file uses this strategy

https://github.com/tornadoweb/tornado/blob/master/.travis.yml
`    - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then (cd ../docs && mkdir sphinx-out && sphinx-build -E -n -W -b html . sphinx-out); fi `

**Pull request merged**
