### PR TITLE
Change Theano references to Aesara

### PR DESCRIPTION
**Pull request by brandonwillard**
This PR renames Theano to Aesara.  It complements the changes in https://github.com/pymc-devs/pymc3/pull/4471.

### CODE REVIEW

**Review by OriolAbril — COMMENTED** [review]
Thanks, it looks like we have to ignore a couple pylint warnings and it's good to merge

**Comment by brandonwillard** [comment]
The [current errors](https://dev.azure.com/ArviZ/ArviZ/_build/results?buildId=3919&view=logs&j=af9a1d3a-ff8f-5483-6823-86518c773a9b&t=d1f9f1df-bd17-5f75-5a7b-8e272c593e8b&l=88) don't look related to these changes.  Now, they involve Stan code.

**Comment by brandonwillard** [comment]
Did something change among the Stan-based dependencies (e.g. a new version causing an issue)?

**Comment by OriolAbril** [comment]
> Did something change among the Stan-based dependencies (e.g. a new version causing an issue)?

Yes, #1558 will fix it

**Pull request merged**
