### PR TITLE
Update docs

### PR DESCRIPTION
**Pull request by ColCarroll**
This tidies the docs up a bit. Will need someone else to run the notebook without PyStan errors and make a new pr, though...

### CODE REVIEW

**Comment by ColCarroll** [comment]
It is up at https://colindcarroll.com/static/arviz/, but my https certificate needs to be renewed, so maybe no need to go right now.

**Comment by canyon289** [comment]
This explains why I can't get to your blog at work.

**Comment by ColCarroll** [comment]
...it is better now!

**Comment by canyon289** [comment]
I would move the matplotlib magic command to below the header
image

**Comment by ColCarroll** [comment]
This is ready to go - the C++ warnings from pystan in the notebook were ridiculously long, and I edited the notebook by hand. Will have to figure out how to install properly in the future...

**Comment by ahartikainen** [comment]
That is weird thing. What OS do you have?

Wonder if we could run the notebooks on ci?

**Comment by ColCarroll** [comment]
it is ubuntu, running in a conda environment. not a C person, so hard for me to figure out what compiler is getting used - super strangely, the "useful" pystan output (progress bar, convergence warnings, etc) was going to my jupyter console!

**Pull request merged**
