### PR TITLE
implement from_cmdstanpy

### PR DESCRIPTION
**Pull request by ahartikainen**
Implements `from_cmdstanpy`

Also fixes `convert` function to correctly handle different special groups and enables also `from_cmdstan` if input is a `list` or `str` that endswith `.csv`.

### CODE REVIEW

**Comment by ahartikainen** [comment]
I think I will add tests later. This currently at least working locally.

(I need to think how we should do the testing, because I don't want to install CmdStan to our test env, might need to.)

**Comment by canyon289** [comment]
> I think I will add tests later. This is currently working locally.
> 
> (I need to think how we should do the testing, because I don't want to install CmdStan to our test env, might need to.)

Could the outputs of cmdstan be stored and we test against that?

**Comment by ahartikainen** [comment]
Not really. (Or maybe). It is still in beta, so things might change in future.

Maybe we could read the csv files and transform them to PosteriorSample.

**Comment by ahartikainen** [comment]
Will merge now, let's figure out testing later (cmdstanpy is still beta, so it might still change)

**Pull request merged**
