### PR TITLE
Issue/1825 add docs references to plot posterior docstring

### PR DESCRIPTION
**Pull request by Divyateja04**
## Description
Changes Made:
Added `backend_kwargs`, and also added a see also section

## Checklist

- [x] Follows [official](https://github.com/arviz-devs/arviz/blob/main/CONTRIBUTING.md#pull-request-checklist) PR format
- [x] Includes a sample plot to visually illustrate the changes (only for plot-related functions)
- [ ] New features are properly documented (with an example if appropriate)?
- [ ] Includes new or updated tests to cover the new feature
- [x] Code style  correct (follows pylint and black guidelines)
- [ ] Changes are listed in [changelog](https://github.com/arviz-devs/arviz/blob/main/CHANGELOG.md#v0xx-unreleased)

### CODE REVIEW

**Comment by roshnaeem** [comment]
You need to make a new branch from main, that does not have the changes of your last branch.
```
git checkout main
git checkout -b new-branch-name
```

This branch and PR should not have the changes of the last branch.

**Comment by Divyateja04** [comment]
Um I did make a new branch following what you said...on my forked version it does show a different branch, do you mean to say i should merge commits into a different branch than `arviz-devs:main`

**Comment by roshnaeem** [comment]
yes, for every PR you should make a new branch.

**Comment by Divyateja04** [comment]
Okay so I made a new branch on my forked version but didn't make on the actual one...so um how do I do that?
I just run 
```
git checkout main
git checkout -b new-branch-name
``` 
and push again?

**Comment by Divyateja04** [comment]
on my forked repo a new branch is already made, how do I PR to a different branch on arviz-devs is my question(framed it in a better way)

**Comment by roshnaeem** [comment]
On your forked project, you made a new branch `1825-add-docs-references-to-plot_posterior-docstring` when you were on the branch `main`. 
You shouldn't have made changes in the `main` branch in the very first place. because it always creates a mess. 

Always create a new branch before making changes.

**Comment by roshnaeem** [comment]
Now copy your changes somewhere else, to keep a backup.  Create a new branch.

`git checkout -b plot-posterior`

Remove all the changes it has, related to the last PR. You can copy-paste the file https://github.com/arviz-devs/arviz/blob/main/doc/source/user_guide/numpyro_refitting_xr_lik.ipynb from the repo. 

Then make changes in that PR and push those changes.

**Comment by Divyateja04** [comment]
Okay so I reverted all changes back to normal, next I checkout and then edit...is that right?

**Pull request closed without merging**
