### PR TITLE
Plots refactor

### PR DESCRIPTION
**Pull request by OriolAbril**
Opening this to share the first data organization refactor draft. DO NOT MERGE. Not only is is completely unmergeable right now, but it might also be a better idea we coordinate to split the library into modules at the same time we do these changes/rewrite the plots module, in which case it wouldn't even be merged here but to another repo.

----
:books: Documentation preview :books:: https://arviz--2092.org.readthedocs.build/en/2092/

### CODE REVIEW

**Comment by OriolAbril** [comment]
<p>You need ArviZ development version for this to work</p>

---

 <a href='https://app.reviewnb.com/arviz-devs/arviz/pull/2092/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by OriolAbril** [comment]
<p>I have used it sometimes to help differenciate <em>lines</em> (like here with kde) where the points themselves aren't really relevant as we want a continuous-looking line, I struggle a bit with multiple linestyles if the lines have significant overlap. I don't know if that is what it should be used for, I mostly only chose some properties quite at random to show how to customize artists after plotting, there is no meaning nor easter egg to what I used. </p>

---

 <a href='https://app.reviewnb.com/arviz-devs/arviz/pull/2092/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by OriolAbril** [comment]
<p>Having this work with all possible styles will be challenging, hadn't really thought about this at all yet.</p><p> </p>

---

 <a href='https://app.reviewnb.com/arviz-devs/arviz/pull/2092/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sarinac** [comment]
<p>Ok that makes sense. Thanks for explaining! </p><p>My usual way is making the alpha value smaller for the lines I care less about. I think that could also be done the via the same way as your example so that's good. </p>

---

 <a href='https://app.reviewnb.com/arviz-devs/arviz/pull/2092/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sarinac** [comment]
<p>Random edge case - if I change the <code>zorder</code> of any artist, I don't think the ordering within the dataset will change. It'll just no longer reflect the layer order (defaulted as the order in which something was drawn). Maybe this could just exist as a warning/note.</p>

---

 <a href='https://app.reviewnb.com/arviz-devs/arviz/pull/2092/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by OriolAbril** [comment]
<blockquote>Can <code>PlotCollection.wrap</code> have <code>rows=None</code> as an argument (or is this going to be covered with <code>PlotCollection.grid</code>)?</blockquote><p> </p><p>My idea was for .grid to take care of that. I still haven't gotten to writing the method or completely defining the API for it, maybe it could have a way to define extra dims/coords for those asymmetrical plots. I completely overlooked them so I'll have to think about this for a bit.</p><p> </p>

---

 <a href='https://app.reviewnb.com/arviz-devs/arviz/pull/2092/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by OriolAbril** [comment]
<p>All this is taken care of by the labeller_fun. I am using the existing functionality which is designed for datasets. In this case the NoVarLabeller would be a better choice, but when using datasets, the variable name (atts in this case) is no longer repeated in <em>all</em> subplots, only in many of them. The first example in https://python.arviz.org/en/latest/api/generated/arviz.plot_posterior.html shows this, there are many theta ones, one per coordinate, but also a mu and a tau subplot. </p>

---

 <a href='https://app.reviewnb.com/arviz-devs/arviz/pull/2092/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by OriolAbril** [comment]
<p>the ordering won't change, I'll add a note on this in the docs for the class</p>

---

 <a href='https://app.reviewnb.com/arviz-devs/arviz/pull/2092/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sarinac** [comment]
<p>Thanks! That makes sense now. </p><p> </p><p>The only improvement I could think of is using <a href="https://matplotlib.org/stable/gallery/subplots_axes_and_figures/subfigures.html" target="_blank">subfigures</a> (which I have never used before) to group each variable name. </p><p> </p>

---

 <a href='https://app.reviewnb.com/arviz-devs/arviz/pull/2092/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sarinac** [comment]
Hey @OriolAbril , just a thought for the comment regarding `title_artist` / `labeller_fun` / [first example of plot posterior](https://python.arviz.org/en/latest/api/generated/arviz.plot_posterior.html) - I was wondering if using [subfigures](https://matplotlib.org/stable/gallery/subplots_axes_and_figures/subfigures.html) would be the right approach for grouping variables together in a more organized format. I imagine this working for posterior plot and rank plot but maybe not forest plot where everything's in the same axis. 

pros: more organized visual (maybe dataset too)? 
cons: maybe not worth the complexity to implement, chart is less compact

Here are 2 mockups: the subfigure title is the variable name, the axis title is the school, the figure title is blank
* Vertical version
image

* Horizontal version
image

**Pull request closed without merging**
