### PR TITLE
Add ArviZ.jl to readme and docs

### PR DESCRIPTION
**Pull request by OriolAbril**
It also fixes the example of plot_rank with vlines which I saw was not working

### CODE REVIEW

**Comment by sethaxen** [comment]
Maybe it's better to link to ArviZ.jl's documentation: https://arviz-devs.github.io/ArviZ.jl/dev/ since there will ultimately be much more information there. We can update that to the stable docs once the first version is released.

**Comment by OriolAbril** [comment]
Will https://arviz-devs.github.io/ArviZ.jl/latest point to the stable version once present? It seems to already work even though it points to dev version now.

**Comment by sethaxen** [comment]
`latest` always points to `dev` and is now deprecated.

**Comment by sethaxen** [comment]
LGTM

**Pull request merged**
