### PR TITLE
KDE: Display quantiles

### PR DESCRIPTION
**Pull request by aloctavodia**
This add the option to get a KDE segmented into quartiles (or more general quantiles). There are still a few things to fix and improve

gauss_q

expo_q

### CODE REVIEW

**Comment by ahartikainen** [comment]
List of numbers between 0 and 100. Or quantiles => list of numbers between 0 and 1.

Also what algorithm should we use for quantiles etc? Data or kde results?

**Comment by ahartikainen** [comment]
Also, would there be any potential to define ... "symmetric" quantile, e.g. distribution which is constrained and MAP is on one of the constrain?

E.g. 1-tail / 2-tail / negative 1-tail

**Comment by aloctavodia** [comment]
Not sure I truly understand what these "symmetric" quantiles are

**Comment by ahartikainen** [comment]
True, I probably don't understand them either.

I think it similar if we split data based on the density (starting from top, moving horizontal line down until q-quantile of the density is inside the density limits...

**Comment by ahartikainen** [comment]
Good choice

**Comment by aloctavodia** [comment]
Sure! I can add a test, but not until next Tuesday. So if you want to add it sooner than that, please go ahead.

**Comment by canyon289** [comment]
LGTM

**Comment by aloctavodia** [comment]
@ahartikainen are you also OK with this?

**Comment by ahartikainen** [comment]
Lgtm

**Pull request merged**
