### PR TITLE
Added documentation example for combining InferenceData (#552) and also solving the issue of creaton of empty file for better behaviour with inference data(#486)

### PR DESCRIPTION
**Pull request by Shashankjain12**
Added example in the docstring as per the issue number #552

### CODE REVIEW

**Comment by Shashankjain12** [comment]
Why travis-ci is failing to build as my all test cases are solved except python3.6 lint?

**Comment by Shashankjain12** [comment]
## Better behavior with empty InferenceData #486
* Added the code for empty file create according to issue #486 
* Created the test cases for that particular issue #486 
* Added comments for the if-else case

**Comment by canyon289** [comment]
@Shashankjain12 I hate to be the bearer of bad news but  two things
1. This issue is already in progress here, in good faith I can't accept this PR because someone else is already putting effort into it. Before taking on an issue please double check if someone else is working on it
2. Try and do one PR per issue. It makes it much easier to sort things out, large PRs are hard to manage and comment on

My suggestion would be to close this PR and just add documentation for combining inference data

https://github.com/arviz-devs/arviz/pull/577

**Comment by Shashankjain12** [comment]
Ok sure I will close this PR

**Pull request closed without merging**
