### PR TITLE
Remove get_samples calls from Predictive in cookbook

### PR DESCRIPTION
**Pull request by RaulPL**
I just removed the get_samples() calls in the cookbook notebook because numpyro will remove the method in future versions.

### CODE REVIEW

**Comment by OriolAbril** [comment]
Is this for numpyro only or is pyro affected too? cc @fehiepsi

Other than that looks good to me, thanks!

**Review by fehiepsi — APPROVED** [review]
Thanks @RaulPL !

@OriolAbril it is changed in Pyro first, then in NumPyro too.

**Comment by RaulPL** [comment]
Happy to help =)

**Comment by OriolAbril** [comment]
@RaulPL can you update the pyro example too?

**Review by OriolAbril — APPROVED** [review]

**Comment by RaulPL** [comment]
Done.

**Pull request merged**
