### PR TITLE
Fixed plot_trace legend overwriting by chain legend (Issue #2320)

### PR DESCRIPTION
**Pull request by imperorrp**
## Description

Addresses Issue #2320 , where chain legend seemed to overwrite fist subplot legend that displays coord combinations. 

When the chain legend is created (`.legend(handles=handles, title="chain", loc="upper right")`), passing this to second subplot in the plot generated, which is the first trace plot (`ax.figure.axes[1]`) instead of the first subplot, which is the first density plot and already has a legend (`ax.figure.axes[0]`) prevents overwriting. As per @OriolAbril 's suggestion in the issue comments of #2320 . 

Here are the plots now generated with this small edit, with no overwriting:

fixed_traceplot

fixed_traceplot2

## Checklist

- [x] Follows [official](https://github.com/arviz-devs/arviz/blob/main/CONTRIBUTING.md#pull-request-checklist) PR format
- [x] Includes a sample plot to visually illustrate the changes (only for plot-related functions)
- [ ] New features are properly documented (with an example if appropriate)?
- [x] Includes new or updated tests to cover the new feature
- [x] Code style  correct (follows pylint and black guidelines)
- [x] Changes are listed in [changelog](https://github.com/arviz-devs/arviz/blob/main/CHANGELOG.md#v0xx-unreleased)

----
📚 Documentation preview 📚: https://arviz--2334.org.readthedocs.build/en/2334/

### CODE REVIEW

**Comment by imperorrp** [comment]
Test failures seem to be from an issue with checking axes[0,0] for the chain legend- could this test be modified?

**Comment by OriolAbril** [comment]
> Test failures seem to be from an issue with checking axes[0,0] for the chain legend- could this test be modified?

Yes, it needs to be modified. Once you have you can check the " Includes new or updated tests to cover the new feature" box

**Comment by imperorrp** [comment]
> > Test failures seem to be from an issue with checking axes[0,0] for the chain legend- could this test be modified?
> 
> Yes, it needs to be modified. Once you have you can check the " Includes new or updated tests to cover the new feature" box

Sure, will modify test as appropriate

**Review by OriolAbril — COMMENTED** [review]
If you click at the "details" link of the failing job you'll eventually get to this page: https://dev.azure.com/ArviZ/ArviZ/_build/results?buildId=6712&view=logs&jobId=52053870-44e4-57aa-b540-f1a2d094f440&j=52053870-44e4-57aa-b540-f1a2d094f440&t=b4fdbffc-b4d0-53ca-c47c-a902d6813a77.

It looks like there is a trailing whitespace somewhere. You can run black which will get rid of it and if necessary to any other formatting changes needed. With that and adding a line to the Changelog in maintenance and bug fixes section it will be ready to merge.

**Comment by imperorrp** [comment]
> If you click at the "details" link of the failing job you'll eventually get to this page: https://dev.azure.com/ArviZ/ArviZ/_build/results?buildId=6712&view=logs&jobId=52053870-44e4-57aa-b540-f1a2d094f440&j=52053870-44e4-57aa-b540-f1a2d094f440&t=b4fdbffc-b4d0-53ca-c47c-a902d6813a77.
> 
> It looks like there is a trailing whitespace somewhere. You can run black which will get rid of it and if necessary to any other formatting changes needed. With that and adding a line to the Changelog in maintenance and bug fixes section it will be ready to merge.

Sure, just did that. Seems some `doc/` files got formatted too- is that alright or is black formatting not supposed to be run on that folder?

**Comment by OriolAbril** [comment]
It's ok yeah, don't worry.

**Comment by OriolAbril** [comment]
Let's add a bullet point to the changelog to check the last box and merge

**Comment by imperorrp** [comment]
> Let's add a bullet point to the changelog to check the last box and merge

Sure, just did that

**Review by OriolAbril — APPROVED** [review]

**Pull request merged**
