### PR TITLE
use jitted histogram everywhere

### PR DESCRIPTION
**Pull request by aloctavodia**

### CODE REVIEW

**Comment by canyon289** [comment]
LGTM

**Comment by OriolAbril** [comment]
I have just seen many deprecation warnings when building the docs locally (they also happen in travis here but everything seems to work). It looks like they were introduced here. @Ban-zee are these deprecation warnings something to worry about?

**Comment by Ban-zee** [comment]
A deprecation might denote that the particular function is not compatible
with the no python mode anymore which can lead to slowdown of the jitted
function

**Comment by aloctavodia** [comment]
I still not find this when working with ArviZ, I will keep an eye on this and see if this need some change

**Pull request merged**
