### PR TITLE
Tidy up before release 0.3

### PR DESCRIPTION
**Pull request by aloctavodia**

### CODE REVIEW

**Comment by ColCarroll** [comment]
I think you added too many things!

**Comment by ColCarroll** [comment]
Hrm... these notebooks are producing too much output (~6k lines!) from the pystan models. Let me spend a few minutes trying to figure out how to suppress it.

**Comment by canyon289** [comment]
I've been struggling with this and its unfortunately an aging todo item.

https://github.com/stan-dev/pystan/issues/530 for reference

**Comment by ColCarroll** [comment]
Ah yeah, thanks for the reference! I had looked at another (earlier) issue where Bob suggested you can direct output to somewhere else. I :heart: tricksy redirects and have a bunch of :coffee: though...

**Comment by aloctavodia** [comment]
Closing in favor of #445

**Pull request closed without merging**
