### PR TITLE
Start of docker testing

### PR DESCRIPTION
**Pull request by canyon289**
An attempt to run tests in docker

Image builds but tests are failing for what looks like two reasons
* pystan models won't load
>docker run arviz_test pytest arviz/tests/test_data.py

Xarray/netcdf is hitting an assertation errors
> docker run arviz_test pytest arviz/tests/test_data.py::test_convert_to_inference_data_from_file

General notes
* I broke Austin's code temporarily. Will fix once testing is figured out.
* We can test different environments by passing in environmental variables

### CODE REVIEW

**Comment by canyon289** [comment]
Comment in reference to commit 35d3200

@ahartikainen 
When running tests there are failures with loading the model as detailed below

Build container 
> ./scripts/test_docker.sh

Run some of the tests
> docker run arviz_test pytest -vv arviz/tests/test_data.py

Getting this failure 


     draws = 500, chains = 2
 
     def load_cached_models(draws, chains):
         """Load pymc3, pystan, and emcee models from pickle."""
         here = os.path.dirname(os.path.abspath(__file__))
         data = eight_schools_params()
         supported = (
             (pystan, pystan_noncentered_schools),
             (pm, pymc3_noncentered_schools),
             (emcee, emcee_linear_model),
             (pyro, pyro_centered_schools),
         )
         data_directory = os.path.join(here, "saved_models")
         models = {}
         for library, func in supported:
             py_version = sys.version_info
             fname = "{0.major}.{0.minor}_{1.__name__}_{1.__version__}_{2}_{3}.pkl".format(
                 py_version, library, draws, chains
             )
             path = os.path.join(data_directory, fname)
             if not os.path.exists(path):
                 with open(path, "wb") as buff:
                     pickle.dump(func(data, draws, chains), buff)
             with open(path, "rb") as buff:
               models[library.__name__] = pickle.load(buff)
               ModuleNotFoundError: No module named 'stanfit4anon_model_e7aeb8b836685a923269e6171e7377cd_5273131289609479085'
arviz/tests/helpers.py:207: ModuleNotFoundError


Do you know why this might be the case?

I'm getting another NetCDF error as well but I feel more confident digging into that one

**Comment by ahartikainen** [comment]
Something is probably missing from C++ libs.

Try with

    apt-get install build-essential

and if it works, we can go back and try to figure out what is "missing" from manual installation (`gcc, g++, gfortran`.

I think we even could go to `clang/llvm` toolchain later.

**Comment by canyon289** [comment]
> Something is probably missing from C++ libs.
> 
> Try with
> 
> ```
> apt-get install build-essential
> ```


Tried this and it didn't work :( 

Good news is once we get this fixed I believe all tests will pass in docker!

**Comment by ahartikainen** [comment]
Can set it up so that travis would try to run docker? Or are we going to read prebuilt image?

**Comment by canyon289** [comment]
I haven't figured out those details yet, there's pros and cons to each one and I'm not entirely sure what the tradeoffs would be.

**Comment by canyon289** [comment]
This is out of wip and ready for evaluation. 

I've (temporarily) broken the notebook feature to streamline testing. After this is merged I would like to continue by creating additional prs
* Add capability specify python and pystan version through command line flags to --build
* Add build stages so we can cache lower level images e.g cache docker "os" build, cache test model creation
* Add a build stage to reintroduce notebook capability to container

Biggest change is changing base image from jupyter/minimal-notebook to conda/miniconda3
`conda/miniconda3` ended up creating much smaller image (~2 gigs vs 8 gigs) and seems to build faster.

**Comment by ahartikainen** [comment]
Build fails if there are no pickle files. Add `-f` to command

    rm -f ....*.pkl

**Comment by canyon289** [comment]
Don't merge yet. Need to fix issue with segment fault

**Comment by canyon289** [comment]
Fixed issue. Merging

**Pull request merged**
