### PR TITLE
Incorporated input_core_dims in hdi and plot_hdi docstrings 

### PR DESCRIPTION
**Pull request by abhisht51**
## Checklist

- [x] Follows [official](https://github.com/arviz-devs/arviz/blob/master/CONTRIBUTING.md#pull-request-checklist) PR format
- [ ] Includes a sample plot to visually illustrate the changes (only for plot-related functions)
- [ ] New features are properly documented (with an example if appropriate)?
- [ ] Includes new or updated tests to cover the new feature
- [x] Code style  correct (follows pylint and black guidelines)
- [x] Changes are listed in [changelog](https://github.com/arviz-devs/arviz/blob/master/CHANGELOG.md#v0xx-unreleased)

Issue #1400

### CODE REVIEW

**Comment by OriolAbril** [comment]
I think it should now count towards hacktoberfest, and most importantly, thanks for the PR!

**Comment by OriolAbril** [comment]
@abhisht51 can you rebase and add it to the changelog? We can merge then after tests pass

**Comment by abhisht51** [comment]
I don't know how to go about it. I have seen the git rebase command so I will do that and hopefully find the changeling file and modify it to. But then I push again ?? Or do I do it all on GitHub itself ?

**Comment by ahartikainen** [comment]
in arviz folder

    git remote add upstream https://github.com/arviz-devs/arviz
    git remote -v

    git checkout master
    git fetch --all
    git merge upstream/master
    git checkout your-branch
    git rebase -i master

Fix merge errors (e.g. Atom Editor / Vim are options) and call `git add .` and then `git rebase --continue`

    git push -f

**Comment by OriolAbril** [comment]
Also feel free to reach out at [gitter](https://gitter.im/arviz-devs/community) is there were a problem with any of the commands above.

**Comment by ahartikainen** [comment]
This looks good. Can you still add a comment to changelog? You can follow similar format as previous comments. This can go under Documentation

**Comment by abhisht51** [comment]
I will do it by soon!!

**Comment by abhisht51** [comment]
I was unsure if I needed to make the update as a new PR or continue in this one. For now, I have chosen this one.

**Review by ahartikainen — APPROVED** [review]
LGTM

**Comment by ahartikainen** [comment]
> I was unsure if I needed to make the update as a new PR or continue in this one

Good point. Continue is the right choice, we should be explicit about it in the contribution docs.

**Comment by ahartikainen** [comment]
Thanks for the PR

**Pull request merged**
