### PR TITLE
[WIP] Forest plot uses distplot for discrete values. Fixes #599

### LINKED ISSUE #599: Forestplot-ridgeplot: use histograms for discrete variables by default
Internally we should use distplot #592.

### PR DESCRIPTION
**Pull request by Ban-zee**
A very early commit. Will make the necessary changes after a review.

### CODE REVIEW

**Comment by canyon289** [comment]
Can a test be added please?

**Comment by aloctavodia** [comment]
Hi @Ban-zee are you still working on this?

**Comment by Ban-zee** [comment]
Yes, will resume work on this soon.

**Comment by aloctavodia** [comment]
After taking to @Ban-zee I am closing this

**Pull request closed without merging**
