### PR TITLE
Support multichain ppc in plot_ppc

### PR DESCRIPTION
**Pull request by ahartikainen**
Adds support for multichain ppc.

Also implements jitter for scatter and changes alpha defaults for scatter.

### CODE REVIEW

**Comment by ahartikainen** [comment]
I will wait `from_dict` before I implement tests

**Comment by ahartikainen** [comment]
Now the scatter is more flexible

# Data count 30 & 10

image


# Data count 30 & 1000

image

**Comment by ahartikainen** [comment]
Now multimodel works also. There are many moving parts, but I'm glad it works.

image

**Comment by ahartikainen** [comment]
There is something wrong with travis. Forestplot works (I removed problematic code). So I think this can wait until it is merged.

**Comment by canyon289** [comment]
Rebased on master for TravisCI fix

**Comment by ahartikainen** [comment]
LGTM, I will merge this now.

**Pull request merged**
