### PR TITLE
Simplify code (f-strings, dictionary comprehension, if expressions and simplify if statements)

### PR DESCRIPTION
**Pull request by hectormz**
## Description
This PR seeks to simplify `arviz` code and make it easier to read/maintain. Each commit includes a specific change:

* Use f-strings wherever possible
* Use standard single quote character (there were some angled ones that may have come from a word processor)
* Use dictionary comprehension instead of initializing empty dictionaries and looping through key/items
* Use if expressions to simplify simple if statements for assignment
* Simplify remaining if statements to reduce nested levels or negation

## Checklist

- [X] Follows [official](https://github.com/arviz-devs/arviz/blob/main/CONTRIBUTING.md#pull-request-checklist) PR format
- [X] Code style  correct (follows pylint and black guidelines)
- [ ] Changes are listed in [changelog](https://github.com/arviz-devs/arviz/blob/main/CHANGELOG.md#v0xx-unreleased)

### CODE REVIEW

**Comment by OriolAbril** [comment]
Thanks for the PR and sorry for the late response, I'll try to review at some point, won't happen until at least next week though :/

**Comment by hectormz** [comment]
@OriolAbril no worries!

**Comment by hectormz** [comment]
@OriolAbril I updated the PR from the latest version of `main`. Seems there is an issue with `mypy` configuration:

```
2022-07-05T04:03:21.2408966Z WARNING: mypy was not able to find type hints for module 'IPython' since it does not seem to be installed in the current environment. Assuming it has no type hints available.
2022-07-05T04:03:21.2411188Z WARNING: mypy was not able to find type hints for module 'pystan' since it does not seem to be installed in the current environment. Assuming it has no type hints available.
2022-07-05T04:03:21.2412547Z WARNING: mypy was not able to find type hints for module 'aesara' since it does not seem to be installed in the current environment. Assuming it has no type hints available.
2022-07-05T04:03:21.2413853Z WARNING: mypy was not able to find type hints for module 'pystan' since it does not seem to be installed in the current environment. Assuming it has no type hints available.
2022-07-05T04:03:21.2415745Z WARNING: mypy was not able to find type hints for module 'pystan' since it does not seem to be installed in the current environment. Assuming it has no type hints available.
2022-07-05T04:03:21.2416696Z > Mypy was unable to find type hints for some 3rd party modules, configuring mypy to ignore them.
2022-07-05T04:03:21.2417592Z     More info: https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
2022-07-05T04:03:21.2418899Z     Affected modules: ['IPython', 'aesara', 'bokeh', 'cloudpickle', 'emcee', 'matplotlib', 'mpl_toolkits.axes_grid1', 'netCDF4', 'numba', 'numpyro', 'pandas', 'pyjags', 'pymc3', 'pyro', 'pystan', 'scipy', 'setuptools', 'stan', 'theano', 'zarr']
2022-07-05T04:03:21.2419691Z 
2022-07-05T04:11:17.4780685Z Error: The current mypy.ini does not contain the tightest available configuration:
```

**Review by OriolAbril — COMMENTED** [review]
It is not mypy what is failing CI but typing copilot which is actually good news. This means that with these changes we can improve our mypy config to be more strict and remove some ignore clauses for example. 

You can download the updated mypy.ini config written by typing copilot automatically from https://dev.azure.com/ArviZ/ArviZ/_build/results?buildId=5815&view=results in the [published artifacts](https://dev.azure.com/ArviZ/ArviZ/_build/results?buildId=5815&view=artifacts&pathAsName=false&type=publishedArtifacts) section (the mypy one is only uploaded if the typing copilot job fails). 

I also added a couple nits as comments but it looks good other than these minor issues, thanks!

**Comment by hectormz** [comment]
@OriolAbril will make the changes tomorrow. So replacing the `mypy.ini` file with the new artifact should cover it?

**Comment by obi1kenobi** [comment]
> @obi1kenobi any idea what could be going on?

I'm not sure why, but it seems like the version of `mypy` being used is only sometimes reporting that `cmdstan` is missing type hints. As a result, the `mypy` configuration generated by a run where `cmdstan` *isn't* reported as missing type hints is not valid in a `mypy` run where `cmdstan` *is* reported as missing type hints.

As the following commit shows, removing the `cmdstan` block is causing the `mypy` check to break. But when `mypy` is executed by `typing_copilot` to generate the tightest available config, `mypy` doesn't report `cmdstan` as missing type hints and therefore that error isn't suppressed in the generated `mypy` config.
https://github.com/arviz-devs/arviz/pull/2026/commits/2b8e2cbb2f9956f843a2f6bf4863cccac7ce3a5f

To be quite honest, I've become quite frustrated with debugging `mypy`-related breakage recently. Many `mypy` versions aren't actually stable, and frequently include regressions and bugs such as this one. I am just one person doing this in my free time for no pay, and it's unfortunately impossible for me to keep up with adding workarounds to `typing_copilot` at the rate that `mypy` is pushing bugs 😢

Please try to update `mypy` and/or try a few different `mypy` versions and see if there's one that doesn't include this regression. If possible, please also report the issue on the `mypy` repo: you can run `typing_copilot` with the `--verbose` flag to see the exact `mypy` invocations it performs, which will probably be useful when reporting the problem.

**Pull request merged**
