### PR TITLE
copy styles with pip

### PR DESCRIPTION
**Pull request by aloctavodia**
Finally I can copy files during installation using pip

### CODE REVIEW

**Comment by aloctavodia** [comment]
Just a couple of simple examples. I will keep working on these styles, suggestions are welcome :-)

adg
awg

**Comment by agustinaarroyuelo** [comment]
Colors are easily distinguishable, I like it.

**Comment by junpenglao** [comment]
Nice!

**Comment by ahartikainen** [comment]
Nice, how one uses these?

    arviz.style.use('arviz-dark')

**Comment by aloctavodia** [comment]
@ahartikainen 

you are almost right, it is

 `arviz.style.use('arviz-darkgrid')` or `arviz.style.use('arviz-whitegrid')`

I keep the name similar to those used in matplotllib/seaborn, but we can change that

**Comment by ahartikainen** [comment]
That's ok. 

(if anyone wonders, I did ninha edit the last post)

**Pull request merged**
