### PR TITLE
Updated text in PyStan schema example to match PyMC3 example

### PR DESCRIPTION
**Pull request by gth158a**
Documentation update.
- Updated text in notebook as requested in "Update doc-Example of InferenceData schema in PyStan" https://github.com/arviz-devs/arviz/issues/1799 
Looked at PR that updated pymc3 example https://github.com/arviz-devs/arviz/pull/1790 as reference

### CODE REVIEW

**Review by canyon289 — APPROVED** [review]
Waiting for https://github.com/arviz-devs/arviz/pull/1806 before merging

**Comment by roshnaeem** [comment]
Hello @gth158a, can you do me a favor? I have made few changes in the related PR #1790. Can you please do one more commit to keep it same as #1790.

Also, i have opened new issues, you can check and work on them as well.

**Comment by gth158a** [comment]
> Hello @gth158a, can you do me a favor? I have made few changes in the related PR #1790. Can you please do one more commit to keep it same as #1790.
> 
> Also, i have opened new issues, you can check and work on them as well.

👍  sounds good. Can you assign this ticket to me?

**Comment by gth158a** [comment]
@roshnaeem  we should be good to go here! 🤓

**Review by roshnaeem — APPROVED** [review]
Thank you so much @gth158a.

**Comment by gth158a** [comment]
> Thank you so much @gth158a.

My pleasure, @roshnaeem . I am looking forward to start contributing more 👍

**Comment by roshnaeem** [comment]
@gth158a, I have created new issues, you can check them. Let me know if you need any help

**Pull request merged**
