### PR TITLE
Add root directory to conf.py

### PR DESCRIPTION
**Pull request by ColCarroll**
Docs are currently broken. This fixes the docs on my local machine. I don't know why this only popped up now, but probably good to add the root directory to the sphinx build.

This looks like a big PR because `black` ran on `conf.py`, but the only real change is 

```python
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
```

which is a portable way to add `../` to the path.

### CODE REVIEW

**Comment by canyon289** [comment]
Hm every TravisCI job is failing with a segmentation fault. This is really odd

**Comment by ColCarroll** [comment]
will try adding `- travis-sphinx build --nowarn --source=doc -vvv` to the travis.yml later

**Comment by ColCarroll** [comment]
Turns out there's no `-vvv` command! I am going to merge this so I can (more easily) build the docs locally, and maybe just push them manually for a little while.

**Comment by ahartikainen** [comment]
Interesting, have there ever been that or is the support dropped?

**Comment by ColCarroll** [comment]
This is the `travis-sphinx` command - not the sphinx command! So this is just for pushing the documentation over to github. 

Took me a while to figure that out...

**Comment by ColCarroll** [comment]
Merging despite the segfault, since it puts us in no worse position with respect to docs building.

**Pull request merged**
