### PR TITLE
enable pyjags tests

### PR DESCRIPTION
**Pull request by ahartikainen**
## Checklist

- [ ] Follows [official](https://github.com/arviz-devs/arviz/blob/main/CONTRIBUTING.md#pull-request-checklist) PR format
- [ ] Includes a sample plot to visually illustrate the changes (only for plot-related functions)
- [ ] New features are properly documented (with an example if appropriate)?
- [ ] Includes new or updated tests to cover the new feature
- [ ] Code style  correct (follows pylint and black guidelines)
- [ ] Changes are listed in [changelog](https://github.com/arviz-devs/arviz/blob/main/CHANGELOG.md#v0xx-unreleased)

### CODE REVIEW

**Comment by ahartikainen** [comment]
Latest jags is somehow broken. I can not install old versions.

**Comment by ahartikainen** [comment]
Ok, something to do with pybind11 and numpy

```
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
terminate called after throwing an instance of 'pybind11::error_already_set'
  what():  SystemError: <built-in method __contains__ of dict object at 0x7f1a143a2c80> returned a result with an error set
/home/vsts/work/_temp/bfd77e72-7add-453a-b1e2-f2bcbe860d6b.sh: line 1:  4549 Aborted                 (core dumped) python -c "import pyjags"
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
terminate called after throwing an instance of 'pybind11::error_already_set'
  what():  SystemError: <built-in method __contains__ of dict object at 0x7f3da224fc80> returned a result with an error set
/home/vsts/work/_temp/bfd77e72-7add-453a-b1e2-f2bcbe860d6b.sh: line 2:  4562 Aborted                 (core dumped) python -c "import pytest;import pyjags"
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
terminate called after throwing an instance of 'pybind11::error_already_set'
  what():  SystemError: <built-in method __contains__ of dict object at 0x7fb1b62b6c80> returned a result with an error set
/home/vsts/work/_temp/bfd77e72-7add-453a-b1e2-f2bcbe860d6b.sh: line 3:  4569 Aborted                 (core dumped) python -c "import pyjags;import pkg_resources;version = pkg_resources.get_distribution(pyjags).version;print(version)"
```

cc @michaelnowotny

**Comment by ahartikainen** [comment]
Ok, numpy 1.20 is installed in the main step, and then some package downgrades it. This breaks something in pypi package resolution --> wrong numpy api apparently. Trying to manually upgrade numpy.

**Comment by ahartikainen** [comment]
Ok, tensorflow needs numpy ~=19.3 and this causes pyjags to fail.

Either we wait until tensorflow updates it's requirements or we comment out the pyjags import from the tests?

**Comment by OriolAbril** [comment]
I reenabled pyjags tests in #1928 so this is no longer necessary

**Pull request closed without merging**
