### PR TITLE
Update from_cmdstanpy converter to follow schema convention

### PR DESCRIPTION
**Pull request by utkarsh-maheshwari**
## Description
Matched sample stats according to InferenceData schema specification in from_cmdstanpy converter. Addreses issue #1514

## Checklist

- [ ] Follows [official](https://github.com/arviz-devs/arviz/blob/main/CONTRIBUTING.md#pull-request-checklist) PR format
- [ ] Code style  correct (follows pylint and black guidelines)
- [ ] Changes are listed in [changelog](https://github.com/arviz-devs/arviz/blob/main/CHANGELOG.md#v0xx-unreleased)

### CODE REVIEW

**Comment by OriolAbril** [comment]
Hi @utkarsh-maheshwari sorry for the inconvenience, a new cmdstanpy version was released and broke the ci tests, so we merged a fix before merging this PR. You'll now need to rebase/merge the latest changes and most importantly, handle the merge conflicts that arise. Not sure if you have ever handled merge conflicts, if you need help let us know

**Comment by OriolAbril** [comment]
Note: also fix the links in the first bullet point of changelog.

**Comment by utkarsh-maheshwari** [comment]
> Not sure if you have ever handled merge conflicts, if you need help let us know

Okay, I would like to attempt it first and would seek help if any issue is there. Thanks!

**Comment by OriolAbril** [comment]
Thanks @utkarsh-maheshwari

**Pull request merged**
