### PR TITLE
[WIP] Changed import files and modified .gitignore

### LINKED ISSUE #1048: Cookbook entry for cmdstanpy outdated
**Describe the bug**

The "Inference Data Cookbook" is outdated for CmdStanPy.

This no longer works:
```python
from cmdstanpy import Model, StanFit
```

Replace with 

```python
from cmdstanpy import CmdStanModel
```
and then replace in the code below `Model` with `CmdStanModel`.

`StanFit` is no longer needed.

### PR DESCRIPTION
**Pull request by amukh18**
## Checklist

- [ ] Does the PR follow [official](https://github.com/arviz-devs/arviz/blob/master/CONTRIBUTING.md#pull-request-checklist) 
      PR format?
- [ ] Has included a sample plot to visually illustrate the changes? (only for plot-related functions)
- [ ] Is the new feature properly documented with an example?
- [ ] Does the PR include new or updated tests to cover the new feature (using [pytest fixture pattern](
      https://docs.pytest.org/en/latest/fixture.html#fixture))?
- [ ] Is the code style correct (follows pylint and black guidelines)?
- [ ] Is the change listed in [changelog](https://github.com/arviz-devs/arviz/blob/master/CHANGELOG.md#v0xx-unreleased )?

Changed import files and added a file that may have been accidentally removed in a previous commit
Fixes #1048

### CODE REVIEW

**Comment by amukh18** [comment]
@ahartikainen I apologise but I have let another person who is new to this repo work on this issue. I will close this pull request.

**Comment by canyon289** [comment]
@amukh18 per convention you had a PR open and commented on issue first.  Please feel free to continue this work. There is a lot of help needed in ArviZ so we have lots of things for folks to work on

**Comment by canyon289** [comment]
@amukh18 It looks like there's a conflict. Do you feel comfortable with next steps to resolve the conflict or would like you like some guidance?

**Comment by amukh18** [comment]
@canyon289  The conflict seems to arise due to the fact that I am using a newer version of Python than the notebook was in. Should I change the version to 3.7.4 or keep it as 3.6.9?

**Comment by ahartikainen** [comment]
We don't need the eight_schools.stan file, because it is created inside the notebook.

I didn't want to have external files --> everything can be seen inside that notebook

```
with open("./eight_school.stan", "w") as f:
    print(schools_code, file=f)
```

**Comment by OriolAbril** [comment]
Should `eight_school.stan` be added then @ahartikainen ? Maybe it would be better to include it in `.gitignore` since it is automatically generated?

> Should I change the version to 3.7.4 or keep it as 3.6.9?

Everything should work in both python 3.7 and 3.6, no need to change it

**Comment by ahartikainen** [comment]
Can .gitignore handle specific folders?

I'm not saying we are never going to have eight_school.stan file, just that this notebook should not use it.

**Comment by ahartikainen** [comment]
I think it can. This should work

    /doc/notebooks/*.stan

@amukh18 btw remember to `git pull` before you start work again, I did some changes to your PR.

**Pull request merged**
