### PR TITLE
Remove parallel from arviz.utils.full (fixes #904)

### LINKED ISSUE #904: Remove parallel from `arviz.utils.full`?
**Describe the bug**
There is nothing to be parallelized.

**To Reproduce**

```
import arviz as az
import os
os.environ["NUMBA_PARALLEL_DIAGNOSTICS"] = "4"

az.utils.full((1000,1000,4), 0)

```

On Windows
```
================================================================================
 Parallel Accelerator Optimizing:  Function full, 
c:\users\ahartikainen\github\arviz\arviz\utils.py (319)  
================================================================================


Parallel loop listing for  Function full, c:\users\ahartikainen\github\arviz\arviz\utils.py (319) 
-----------------------------------|loop #ID
@conditional_jit(parallel=True)    | 
def full(shape, x):                | 
    """Jitting numpy full."""      | 
    return np.full(shape, x)       | 
--------------------------------- Fusing loops ---------------------------------
Attempting fusion of parallel loops (combines loops with similar properties)...
----------------------------- Before Optimisation ------------------------------
--------------------------------------------------------------------------------
------------------------------ After Optimisation ------------------------------
Parallel structure is already optimal.
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
 
---------------------------Loop invariant code motion---------------------------

Instruction hoisting:
No instruction hoisting found
--------------------------------------------------------------------------------
```

**Expected behavior**

**Additional context**
Versions of `arviz` and other libraries used, operating system used, and anything else that may be useful.

### PR DESCRIPTION
**Pull request by nitishp25**
Removed parallel arguement from numba @conditional_jit in arviz.utils.full

fixes #904

### CODE REVIEW

**Comment by nitishp25** [comment]
@OriolAbril Please review :)

**Comment by OriolAbril** [comment]
Hi, you should rebase your `remove-parallel-from-full` branch. If you have followed the steps in the [contributing guide](https://github.com/arviz-devs/arviz/blob/master/CONTRIBUTING.md#steps) you will only need these two lines from step 5:

```
$ git fetch upstream
$ git rebase upstream/master
```

Otherwise you will have to add the upstream remote as explained in step 2:

```
$ git remote add upstream git@github.com:arviz-devs/arviz.git
```

**Comment by nitishp25** [comment]
@OriolAbril I had added upstream earlier and just fetched and rebased it but there appears to be no change. 
I also did that before push changed to my own repo.

**Comment by nitishp25** [comment]
Please review now @OriolAbril

**Pull request merged**
