### PR TITLE
Remove numpy restriction

### PR DESCRIPTION
**Pull request by ahartikainen**
Jax was updated 2020-01-08.

### CODE REVIEW

**Comment by ahartikainen** [comment]
Ok, we are waiting for the new release for numpyro.

https://pypi.org/project/numpyro/#history

**Comment by ahartikainen** [comment]
@fehiepsi and @neerajprad do you have any schedule for the next release?

**Comment by fehiepsi** [comment]
Hi @ahartikainen , we will have it released next week. Will it block your plan?

**Comment by ahartikainen** [comment]
No, this just waiting so I don't forget

**Comment by fehiepsi** [comment]
@ahartikainen We just made a new release for NumPyro. :)

**Comment by ahartikainen** [comment]
Hi, congrats :)

I think I need to also make small fix to pickle

    get_potential_fn.<locals>.postprocess_fn

**Comment by fehiepsi** [comment]
Oppss, that's a breaking change. We should add to the release note. Thanks for pointing out!

**Comment by OriolAbril** [comment]
Also maybe we should update pyro old version in the second build? It is currently 0.5.1

**Comment by OriolAbril** [comment]
LGTM

**Pull request merged**
