### PR TITLE
Switch to `compact=True` by default

### PR DESCRIPTION
**Pull request by Justin-1993**
## Description

Switch to `compact=True` by default in our plots #1468

## Checklist

- [x] Follows [official](https://github.com/arviz-devs/arviz/blob/master/CONTRIBUTING.md#pull-request-checklist) PR format
- [x] New features are properly documented (with an example if appropriate)?
- [ ] Includes new or updated tests to cover the new feature
- [x] Code style  correct (follows pylint and black guidelines)
- [x] Changes are listed in [changelog](https://github.com/arviz-devs/arviz/blob/master/CHANGELOG.md#v0xx-unreleased)

### CODE REVIEW

**Review by AlexAndorra — COMMENTED** [review]
Thanks @Justin-1993, and well done on your first contribution 🍾 

This looks good. Tests are failing [because of an unrelated CI issue](https://dev.azure.com/ArviZ/ArviZ/_build/results?buildId=3690&view=logs&j=c386d60b-d885-573f-0dc9-50acbfdb69a9&t=c10daa47-4c46-5692-7e81-5600bbd0e0b2&l=15) (#1471). I'll relaunch them once this issue is settled and merge once they pass 😉 

Just a quick suggestions for your future (numerous) PRs (😉): try to use more informative names for your branches and PR titles. This is better practice for reviewers and our future selves. 
If you need a bit of guidance on the fundamentals of git (which, granted, is confusing at first!), the first 3 chapters of [this book](https://git-scm.com/book/en/v2) are really good 👌

**Comment by canyon289** [comment]
Thank you for the contribution!

This PR just needs a rebase on master to pickup the latest CI changes that got merged.

**Comment by Justin-1993** [comment]
@AlexAndorra thank you for the feedback. I will definitely be checking out that book you suggested. 😁

**Comment by AlexAndorra** [comment]
You're welcome @Justin-1993 😉 
To pick up the latest changes from master, while making sure you're on `new_branch`, you can just do:
```
git fetch upstream
git merge upstream/main
```
Then you should see changes picked up locally, and you just have to do `git push` to push them here, which will trigger the automated tests again

**Comment by Justin-1993** [comment]
Hi @AlexAndorra I did what you said and it looks like all tests have now passed 😃

**Review by AlexAndorra — APPROVED** [review]
All good now, thanks @Justin-1993 🎉

**Comment by canyon289** [comment]
@Justin-1993 Thank you so much for this. Happy holidays wherever you are

**Pull request merged**
